/**
 * v35 · VERTICAL CATALOG · «اسپرت و پوشاک» (Sport & Fashion)
 * -------------------------------------------------------------------
 * PURE DATA — the complete seed catalog for the fashion vertical:
 * 9 categories, 8 brands and 20 REAL products (Persian names, real
 * تومان prices, discounts, stock, ratings, 4–6 Persian specs each and
 * stable OSS images from image-search on z-cdn.chatglm.cn).
 *
 * Consumed by src/app/api/admin/vertical/route.ts (reseed on switch) and
 * rendered through the "sport-fashion" storefront template (editorial
 * cream/coral sport style).
 */

import type { VerticalDef } from "./types";

export const FASHION_CATALOG: VerticalDef = {
  id: "fashion",
  nameFa: "اسپرت و پوشاک",
  nameEn: "Sport & Fashion",
  templateId: "sport-fashion",
  taglineFa: "پوشاک ورزشی و استریت‌ور",
  descFa:
    "فروشگاه تخصصی کفش، پوشاک و اکسسوری ورزشی برندهای معتبر جهان؛ از کفش دویدن حرفه‌ای تا استریت‌ور روزمره. انتخاب استایل، سایز و ست مناسب را به مشاور هوشمند ما بسپارید.",
  icon: "Shirt",

  /* ── AI persona — «استایلیست ورزشی» ─────────────────────────────── */
  aiPersona:
    "تو استایلیست شخصی ورزشی این فروشگاه هستی و به کفش، پوشاک و اکسسوری ورزشی تسلط کامل داری. کاربر را در انتخاب سایز درست (بر اساس قد، وزن و اندازه‌های بدن)، پارچه مناسب (نفس‌گیر، ضد تعریق، گرم‌کن) و ست‌کردن استایل کمک می‌کنی؛ برای دویدن، باشگاه، یوگا یا استایل روزمره پیشنهاد دقیق و کاربردی می‌دهی. همیشه محصولات همین فروشگاه را با نام و قیمت دقیق پیشنهاد می‌کنی و رنگ‌های هماهنگ و ست‌های کامل را هم معرفی می‌کنی. اگر سؤال کاربر خارج از حوزه پوشاک و مد ورزشی باشد (مثل موبایل، لوازم خانگی یا سؤالات عمومی غیرمرتبط)، مؤدبانه توضیح می‌دهی که تخصصت فقط استایل و پوشاک ورزشی است و او را به همان موضوع برمی‌گردانی. لحن تو صمیمی، انرژی‌بخش و مثل یک دوست ورزشکار است و پاسخ‌ها را کوتاه، عملی و به فارسی روان می‌دهی.",

  /* ── 9 categories ────────────────────────────────────────────────── */
  categories: [
    { name: "کفش ورزشی", slug: "shoes", icon: "Footprints", description: "کفش دویدن، تمرین و روزمره برندهای معتبر", sortOrder: 1 },
    { name: "تی‌شرت و پیراهن", slug: "tshirts", icon: "Shirt", description: "تی‌شرت و پیراهن‌های ورزشی نفس‌گیر و خنک", sortOrder: 2 },
    { name: "هودی و سویشرت", slug: "hoodies", icon: "Layers", description: "هودی و سویشرت‌های fleece برای روزهای خنک", sortOrder: 3 },
    { name: "شلوار ورزشی", slug: "pants", icon: "PersonStanding", description: "شلوار دویدن، تمرین و یوگا", sortOrder: 4 },
    { name: "کاپشن و جلیقه", slug: "jackets", icon: "Wind", description: "کاپشن بادگیر و جلیقه‌های پفی", sortOrder: 5 },
    { name: "ست‌های ورزشی", slug: "sets", icon: "Sparkles", description: "ست‌های دو تکه تمرین و دویدن", sortOrder: 6 },
    { name: "اکسسوری ورزشی", slug: "accessories", icon: "Watch", description: "کلاه، دستکش و اکسسوری تمرین", sortOrder: 7 },
    { name: "ساک و کوله", slug: "bags", icon: "Backpack", description: "ساک ورزشی و کوله‌های روزمره", sortOrder: 8 },
    { name: "لباس راحتی", slug: "loungewear", icon: "Moon", description: "پوشاک راحتی و استریت‌ور خانه", sortOrder: 9 },
  ],

  /* ── 8 brands ────────────────────────────────────────────────────── */
  brands: [
    { name: "نایک", slug: "nike" },
    { name: "آدیداس", slug: "adidas" },
    { name: "پما", slug: "puma" },
    { name: "ریباک", slug: "reebok" },
    { name: "نیوبالانس", slug: "newbalance" },
    { name: "آندر آرمور", slug: "underarmour" },
    { name: "اسیکس", slug: "asics" },
    { name: "لاکاست", slug: "lacoste" },
  ],

  /* ── 20 products (real names, real تومان prices) ─────────────────── */
  products: [
    /* ── کفش ورزشی ─────────────────────────────────────────────────── */
    {
      key: "fashion-nike-pegasus-41",
      name: "کفش ورزشی نایک Air Zoom Pegasus 41 مردانه",
      nameEn: "Nike Air Zoom Pegasus 41 Men's Running Shoe",
      price: 4780000,
      discountPrice: 3990000,
      stock: 24,
      categorySlug: "shoes",
      brandName: "نایک",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b9aaa4d487e3.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/1b8a1a606b4a.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d5b830345afc.png",
      ],
      rating: 4.8,
      reviewCount: 214,
      soldCount: 380,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "جنس رویه", value: "مش مهندسی‌شده تک‌لایه" },
        { key: "سایزبندی", value: "۴۰ تا ۴۶ (EU)" },
        { key: "رنگ", value: "سفید / مشکی / خاکستری" },
        { key: "کاربرد", value: "دویدن جاده و تمرین روزمره" },
        { key: "تکنولوژی", value: "Air Zoom + فوم ReactX" },
      ],
      description:
        "پگاسوس ۴۱ نسل جدید محبوب‌ترین کفش دویدن نایک است با میان‌فوم ReactX که ۱۳٪ بازگشت انرژی بیشتری نسبت به نسل قبل دارد. کف آن برای انواع کف پا از قوس معمولی گرفته تا قوس بلند مناسب است و برای دویدن‌های روزانه و نیمه‌استقامتی عالی عمل می‌کند.",
      sku: "FAS-SHO-001",
    },
    {
      key: "fashion-adidas-ultraboost-light",
      name: "کفش ورزشی آدیداس Ultraboost Light مردانه",
      nameEn: "Adidas Ultraboost Light Men's Running Shoe",
      price: 6450000,
      discountPrice: 5290000,
      stock: 18,
      categorySlug: "shoes",
      brandName: "آدیداس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ebbc63dc75e9.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d78a1e0b6ed7.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/bb0768ac9b9f.jpg",
      ],
      rating: 4.7,
      reviewCount: 186,
      soldCount: 240,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "جنس رویه", value: "Primeknit+ بافت یکپارچه" },
        { key: "سایزبندی", value: "۴۰ تا ۴۵.۵ (EU)" },
        { key: "رنگ", value: "مشکی / سفید / Core Black" },
        { key: "کاربرد", value: "دویدن شهری و استایل روزمره" },
        { key: "تکنولوژی", value: "میان‌فوم Boost سبک‌شده (Light)" },
      ],
      description:
        "اولترابوست لایت با ۳۰٪ سبک‌تر شدن میان‌فوم بوست، راحتی مرحله‌ای جدیدی برای دویدن و پیاده‌روی طولانی ساخته است. رویه Primeknit+ مثل جوراب دور پا می‌پیچد و همین ویژگی آن را به انتخابی دو-کاربردی — هم برای تمرین و هم استریت‌ور — تبدیل کرده است.",
      sku: "FAS-SHO-002",
    },
    {
      key: "fashion-puma-velocity-nitro-3",
      name: "کفش ورزشی پما Velocity Nitro 3 زنانه",
      nameEn: "Puma Velocity Nitro 3 Women's Running Shoe",
      price: 4120000,
      stock: 31,
      categorySlug: "shoes",
      brandName: "پما",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c89284a2372d.jpeg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/09d9fc353a3a.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/aa52f338a38b.jpg",
      ],
      rating: 4.5,
      reviewCount: 98,
      soldCount: 150,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس رویه", value: "مش مهندسی‌شده سبک و نفس‌گیر" },
        { key: "سایزبندی", value: "۳۶ تا ۴۲ (EU)" },
        { key: "رنگ", value: "Puma White / صورتی" },
        { key: "کاربرد", value: "دویدن جاده و تمرین سرعتی" },
        { key: "تکنولوژی", value: "فوم Nitro تزریق نیتروژن" },
      ],
      description:
        "ولسیتی نیترو ۳ با میان‌فوم نیتروژنی فوق‌سبک، پاسخ‌دهی سریعی در گام‌های سرعتی می‌دهد و برای تمرین‌های تمپو و دویدن روزانه زنان طراحی شده است. طراحی باریک قوس آن دست پا را در تمام مسیر قفل می‌کند.",
      sku: "FAS-SHO-003",
    },
    {
      key: "fashion-newbalance-1080v14",
      name: "کفش ورزشی نیوبالانس Fresh Foam X 1080 v14 مردانه",
      nameEn: "New Balance Fresh Foam X 1080 v14 Men's Running Shoe",
      price: 8900000,
      discountPrice: 7450000,
      stock: 12,
      categorySlug: "shoes",
      brandName: "نیوبالانس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/50690050aebc.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8bc068a86ba4.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9600415a0e96.jpg",
      ],
      rating: 4.9,
      reviewCount: 260,
      soldCount: 190,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "جنس رویه", value: "Bootie Warp knit یکپارچه" },
        { key: "سایزبندی", value: "۴۱ تا ۴۶ (EU) — عرض D2E" },
        { key: "رنگ", value: "Battlefield Grey / Navy" },
        { key: "کاربرد", value: "دویدن استقامتی و پیاده‌روی طولانی" },
        { key: "تکنولوژی", value: "Fresh Foam X + زیره Vend" },
      ],
      description:
        "۱۰۸۰ نسخه ۱۴ نرم‌ترین و لوکس‌ترین کفش دویدن نیوبالانس است؛ فوم Fresh Foam X مثل بالش مسیر را برای پا نرم می‌کند و رویه Warp Knit بدون درز آن حس جوراب می‌دهد. برای کسانی که بیشترین اولویت‌شان راحتی در کیلومترهای طولانی است، انتخاب اول است.",
      sku: "FAS-SHO-004",
    },
    {
      key: "fashion-asics-gelkayano-31",
      name: "کفش ورزشی اسیکس Gel-Kayano 31 زنانه",
      nameEn: "Asics Gel-Kayano 31 Women's Running Shoe",
      price: 6890000,
      stock: 15,
      categorySlug: "shoes",
      brandName: "اسیکس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/21a452535b44.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cbc4b79510d9.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7bc6b2b9a048.jpg",
      ],
      rating: 4.6,
      reviewCount: 120,
      soldCount: 96,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس رویه", value: "مش مهندسی‌شده 4D Guidance" },
        { key: "سایزبندی", value: "۳۶ تا ۴۱ (EU)" },
        { key: "رنگ", value: "کرم / آبی روشن Sheet Rock" },
        { key: "کاربرد", value: "دویدن استقامتی و اصلاح قوس پا" },
        { key: "تکنولوژی", value: "FF Blast Plus + ژل ۴D" },
      ],
      description:
        "کیانو ۳۱ پایدارترین کفش کلاس Stability بازار است و برای دوندگان با قوس پا صاف یا پرونیشن خفیف ساخته شده است. سیستم راهنمای ۴ بعدی اسیکس، پا را در مسیر صحیح نگه می‌دارد تا آخر کیلومترها بدون خستگی اضافه بدود.",
      sku: "FAS-SHO-005",
    },

    /* ── تی‌شرت و پیراهن ───────────────────────────────────────────── */
    {
      key: "fashion-asics-seamless-tee",
      name: "تی‌شرت ورزشی اسیکس Seamless Short Sleeve مردانه",
      nameEn: "Asics Seamless Short Sleeve Men's Running Tee",
      price: 1290000,
      stock: 0,
      categorySlug: "tshirts",
      brandName: "اسیکس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7c9dc0529c64.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/371c7b4f9e54.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7922b8d84b11.jpg",
      ],
      rating: 4.4,
      reviewCount: 34,
      soldCount: 410,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "پلی‌استر بدون درز (Seamless)" },
        { key: "سایزبندی", value: "S تا XXL" },
        { key: "رنگ", value: "مشکی / سرمه‌ای" },
        { key: "کاربرد", value: "دویدن و تمرین هوازی" },
        { key: "ویژگی", value: "ضد تعریق و سریع‌خشک‌شونده" },
      ],
      description:
        "تی‌شرت بدون درز اسیکس با بافت یکپارچه‌اش هیچ نقطه اصطکاکی روی پوست ندارد و برای تمرین‌های طولانی و هوای گرم فوق‌العاده است. پارچه موپر سریع رطوبت را از بدن دور می‌کند تا همیشه خشک و خنک بمانید.",
      sku: "FAS-TSH-006",
    },
    {
      key: "fashion-lacoste-sport-polo",
      name: "پیراهن پولو لاکاست Sport مردانه",
      nameEn: "Lacoste Sport Men's Polo Shirt",
      price: 2150000,
      stock: 22,
      categorySlug: "tshirts",
      brandName: "لاکاست",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/359505586ae1.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/922c29d2ff9a.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4b4a14b47265.jpg",
      ],
      rating: 4.5,
      reviewCount: 62,
      soldCount: 175,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "جنس", value: "پنبه ۵۰٪ + پلی‌استر ضد چروک" },
        { key: "سایزبندی", value: "S تا XXL" },
        { key: "رنگ", value: "سفید / آبی پولو / سبز" },
        { key: "کاربرد", value: "استایل اسپرت روزمره و تنیس" },
        { key: "ویژگی", value: "یقه ریب بافته + تمساح سوزن‌دوزی" },
      ],
      description:
        "پولو اسپرت لاکاست ترکیب پنبه نرم و الیاف تنفس‌پذیر است که هم در باشگاه خنک نگه‌تان می‌دارد و هم با شلوار جین یا شلوار ورزشی یک استایل استریت‌ور کامل می‌سازد. یقه ریب بعد از شست‌وشوهای مکرر فرم خود را از دست نمی‌دهد.",
      sku: "FAS-TSH-007",
    },

    /* ── هودی و سویشرت ─────────────────────────────────────────────── */
    {
      key: "fashion-nike-club-fleece-hoodie",
      name: "هودی نایک Club Fleece مردانه",
      nameEn: "Nike Club Fleece Men's Hoodie",
      price: 2890000,
      stock: 28,
      categorySlug: "hoodies",
      brandName: "نایک",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/855a4a202c45.webp",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f95b85f3c3d0.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4e15b1a5baf9.jpg",
      ],
      rating: 4.7,
      reviewCount: 158,
      soldCount: 520,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "فلامه پنبه ۸۰٪ / پلی‌استر ۲۰٪" },
        { key: "سایزبندی", value: "S تا XXL" },
        { key: "رنگ", value: "مشکی / خاکستری Stone / کرم" },
        { key: "کاربرد", value: "گرم‌کردن، استایل روزمره و استریت‌ور" },
        { key: "ویژگی", value: "داخل پرزدار + کاپشن دو جیبی" },
      ],
      description:
        "هودی Club Fleece نایک پرفروش‌ترین هودی استریت‌ور چند سال اخیر است؛ فلامه ضخیم و نرمش بعد از ده‌ها بار شست‌وشو هنوز فرم و لطافت روز اول را دارد. برش استاندارد آن با شلوار جوگری همان استایل ریکاوری بعد از تمرین را کامل می‌کند.",
      sku: "FAS-HOO-008",
    },
    {
      key: "fashion-adidas-3stripes-hoodie",
      name: "سویشرت هودی آدیداس 3-Stripes زنانه",
      nameEn: "Adidas 3-Stripes Women's Hoodie",
      price: 2650000,
      discountPrice: 2190000,
      stock: 19,
      categorySlug: "hoodies",
      brandName: "آدیداس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/06506fe58136.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7a15de09f556.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f103f2029436.jpg",
      ],
      rating: 4.4,
      reviewCount: 87,
      soldCount: 260,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "فلامه French Terry پنبه/پلی‌استر" },
        { key: "سایزبندی", value: "XS تا XL" },
        { key: "رنگ", value: "صورتی / مشکی / Lavender" },
        { key: "کاربرد", value: "گرم‌کردن، یوگا و استایل روزمره" },
        { key: "ویژگی", value: "سه نوار کلاسیک آدیداس روی آستین" },
      ],
      description:
        "هودی سه‌نوار آدیداس با برش زنانه و فلامه سبک French Terry، انتخابی همه‌کاره برای قبل و بعد تمرین است. یقه دو لایه و کش‌ساز آستینش گرما را نگه می‌دارد بدون آنکه حجیم به نظر برسد.",
      sku: "FAS-HOO-009",
    },

    /* ── شلوار ورزشی ───────────────────────────────────────────────── */
    {
      key: "fashion-nike-drifit-challenger-pants",
      name: "شلوار ورزشی نایک Dri-FIT Challenger مردانه",
      nameEn: "Nike Dri-FIT Challenger Men's Training Pants",
      price: 2180000,
      stock: 26,
      categorySlug: "pants",
      brandName: "نایک",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2413cac6d6e4.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e2365c8e5796.png",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/04ebe09edee4.jpg",
      ],
      rating: 4.5,
      reviewCount: 76,
      soldCount: 310,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "پلی‌استر Dri-FIT کشسان" },
        { key: "سایزبندی", value: "S تا XXL" },
        { key: "رنگ", value: "مشکی / خاکستری Dark Grey" },
        { key: "کاربرد", value: "دویدن، گرم‌کردن و تمرین" },
        { key: "تکنولوژی", value: "Dri-FIT ضد رطوبت + زیپ مچ" },
      ],
      description:
        "شلوار چلنجر با پارچه Dri-FIT رطوبت را سریع خارج می‌کند و کشش چهار جهته‌اش آزادی حرکت کامل در اسکوات و دویدن می‌دهد. دو جیبی عمق دار زیپ‌دار برای نگه‌داشتن کلید و گوشی هنگام تمرین تعبیه شده است.",
      sku: "FAS-PAN-010",
    },
    {
      key: "fashion-reebok-yoga-nwt-leggings",
      name: "شلوار یوگا ریباک Yoga N.W.T زنانه",
      nameEn: "Reebok Yoga N.W.T Women's Leggings",
      price: 1890000,
      discountPrice: 1590000,
      stock: 34,
      categorySlug: "pants",
      brandName: "ریباک",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ee2ebf63cf54.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2cb0c0151277.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/a570de0d55e7.jpeg",
      ],
      rating: 4.6,
      reviewCount: 141,
      soldCount: 470,
      featured: true,
      isSpecial: true,
      specs: [
        { key: "جنس", value: "نیتریل کشسان بافت شیرونی" },
        { key: "سایزبندی", value: "XS تا XL" },
        { key: "رنگ", value: "مشکی / Burgundy شرابی" },
        { key: "کاربرد", value: "یوگا، پیلاتس و تمرین کششی" },
        { key: "ویژگی", value: "قد بلند High-Rise + کمر پهن بدون لبه" },
      ],
      description:
        "شلوار یوگا N.W.T ریباک با کمر High-Rise بدون فشار و پارچه ضخیم شیرونی، هم پوشش کامل می‌دهد و هم در حرکات عمقی یوگا سر نمی‌خورد. لمس نرم و مات پارچه آن را به انتخاب محبوب استودیو تبدیل کرده است.",
      sku: "FAS-PAN-011",
    },

    /* ── کاپشن و جلیقه ─────────────────────────────────────────────── */
    {
      key: "fashion-nike-windrunner-jacket",
      name: "کاپشن نایک Sportswear Windrunner مردانه",
      nameEn: "Nike Sportswear Windrunner Men's Jacket",
      price: 3690000,
      stock: 16,
      categorySlug: "jackets",
      brandName: "نایک",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/180d85fedd81.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7d273b27be12.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/487035498f5a.jpg",
      ],
      rating: 4.6,
      reviewCount: 104,
      soldCount: 180,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "نایلون رپریپ استوپ" },
        { key: "سایزبندی", value: "S تا XXL" },
        { key: "رنگ", value: "مشکی / Navy / Olive" },
        { key: "کاربرد", value: "بادگیر دویدن و استایل روزمره" },
        { key: "ویژگی", value: "هود تاشو + دم و کف دست تنظیم‌شونده" },
      ],
      description:
        "ویندرانر افسانه‌ای نایک با همان طراحی ۴۴ ساله Chevron روی سینه، حالا با پارچه سبک و ضد آب رپریپ برگشته است. برای روزهای بادی پاییز و بهار، روی هودی یا تی‌شرت بپوشید و هم در تمرین و هم استریت‌ور بدرخشید.",
      sku: "FAS-JAC-012",
    },
    {
      key: "fashion-adidas-down-vest",
      name: "جلیقه پفی آدیداس Down Vest مردانه",
      nameEn: "Adidas Men's Down Vest",
      price: 3290000,
      discountPrice: 2790000,
      stock: 9,
      categorySlug: "jackets",
      brandName: "آدیداس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8e2ee3ec3c06.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/bd3f7b96e9d2.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/54819c9cc776.jpg",
      ],
      rating: 4.3,
      reviewCount: 41,
      soldCount: 74,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "نایلون ریپ‌استاپ با پر طبیعی" },
        { key: "سایزبندی", value: "S تا XXL" },
        { key: "رنگ", value: "مشکی / Black-Ivory" },
        { key: "کاربرد", value: "گرم‌کردن زمستانی و لایه‌بندی" },
        { key: "ویژگی", value: "قابل جمع‌شدن در جیب + جیب داخلی" },
      ],
      description:
        "جلیقه پفی آدیداس با پر طبیعی و قوس‌های افقی دوخته‌شده، هسته بدن را در سرمای شدید گرم نگه می‌دارد و بازوها را آزاد می‌گذارد تا حرکات تمرین محدود نشود. روی هودی بپوشید تا یک استایل لایه‌بندی پاییزی بسازید.",
      sku: "FAS-JAC-013",
    },

    /* ── ست‌های ورزشی ──────────────────────────────────────────────── */
    {
      key: "fashion-ua-training-set",
      name: "ست دو تکه تمرین آندر آرمور مردانه",
      nameEn: "Under Armour Men's 2-Piece Training Set",
      price: 3180000,
      discountPrice: 2680000,
      stock: 14,
      categorySlug: "sets",
      brandName: "آندر آرمور",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6455b8eac89a.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b590fc067407.jpeg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/35ed8c061343.jpg",
      ],
      rating: 4.5,
      reviewCount: 55,
      soldCount: 130,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "پلی‌استر UA Tech خنک" },
        { key: "سایزبندی", value: "S تا XXL (تی‌شرت + شلوار)" },
        { key: "رنگ", value: "مشکی / Charcoal Heather" },
        { key: "کاربرد", value: "تمرین باشگاه و هوازی" },
        { key: "تکنولوژی", value: "خشک‌شونده HeatGear + ضد بو" },
      ],
      description:
        "ست دو تکه آندر آرمور شامل تی‌شرت UA Tech و شلوار کشسان تمرین است که با هم یک ست هماهنگ باشگاهی می‌سازند. پارچه HeatGear در تمرین‌های سنگین خنک و خشک نگه‌تان می‌دارد و تکنولوژی ضد بو آن تازه می‌ماند.",
      sku: "FAS-SET-014",
    },

    /* ── اکسسوری ورزشی ─────────────────────────────────────────────── */
    {
      key: "fashion-puma-classic-cap",
      name: "کلاه کپ پما Archive Logo",
      nameEn: "Puma Archive Logo Cap",
      price: 1150000,
      stock: 40,
      categorySlug: "accessories",
      brandName: "پما",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/753146238aae.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b4ffacb90e12.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f226b441ca38.jpg",
      ],
      rating: 4.2,
      reviewCount: 28,
      soldCount: 640,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "پنبه ارگانیک ۱۰۰٪ توپری" },
        { key: "سایزبندی", value: "فری‌سایز با بند تنظیم" },
        { key: "رنگ", value: "مشکی / Puma White" },
        { key: "کاربرد", value: "دویدن، تنیس و استایل روزمره" },
        { key: "ویژگی", value: "سوزن‌دوزی لوگوی Puma روی جلو" },
      ],
      description:
        "کلاه آرشیو پما با لوگوی کلاسیک پوما و پارچه توپری پنبه، هم زیر آفتاب تمرین محافظت می‌کند و هم مکمل استریت‌ور است. بند تنظیم پشتی آن را برای هر اندازه سر مناسب می‌کند.",
      sku: "FAS-ACC-015",
    },
    {
      key: "fashion-ua-training-gloves",
      name: "دستکش تمرین آندر آرمور Training Grip",
      nameEn: "Under Armour Training Grip Gloves",
      price: 1450000,
      stock: 21,
      categorySlug: "accessories",
      brandName: "آندر آرمور",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cfd255edc57c.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d4def95403da.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/16853033b21d.jpg",
      ],
      rating: 4.1,
      reviewCount: 19,
      soldCount: 220,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "چرم مصنوعی + مش تنفس‌پذیر" },
        { key: "سایزبندی", value: "S تا XL" },
        { key: "رنگ", value: "مشکی / قرمز" },
        { key: "کاربرد", value: "وزنه‌زنی، کراس‌فیت و پارکر" },
        { key: "ویژگی", value: "کف ضد لغزش + مچ بسته‌شونده با ولکرو" },
      ],
      description:
        "دستکش گریپ آندر آرمور با کف چرمی ضد لغزش، کنترل میله را در ست‌های سنگین وزنه‌زنی چند برابر می‌کند. مش پشتی دست تعریق را کنترل می‌کند و ولکرو مچ، بستن دقیق برای هر اندازه دست را ممکن می‌سازد.",
      sku: "FAS-ACC-016",
    },

    /* ── ساک و کوله ────────────────────────────────────────────────── */
    {
      key: "fashion-nike-brasilia-duffle",
      name: "ساک ورزشی نایک Brasilia 9.6",
      nameEn: "Nike Brasilia 9.6 Training Duffel Bag",
      price: 2190000,
      stock: 23,
      categorySlug: "bags",
      brandName: "نایک",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4df3fc310616.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/558fede64b3d.png",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ad118a0c40dd.jpg",
      ],
      rating: 4.7,
      reviewCount: 132,
      soldCount: 350,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "جنس", value: "پلی‌استر ۶۰۰D ضد آب" },
        { key: "سایزبندی", value: "ظرفیت ۴۰ لیتر" },
        { key: "رنگ", value: "مشکی / Navy" },
        { key: "کاربرد", value: "باشگاه، سفر کوتاه ورزشی" },
        { key: "ویژگی", value: "کفش‌دان جدا + جیب ضد رطوبت" },
      ],
      description:
        "ساک برازیلیا نایک با کفش‌دان تهویه‌دار جداگانه، کفش‌های تمرین را از لباس خشک دور نگه می‌دارد. بدنه ۴۰ لیتری آن برای یک جلسه باشگاه یا یک سفر ورزشی دو روزه کاملاً کافی است و بند دوشی دو-جانبه حمل را راحت می‌کند.",
      sku: "FAS-BAG-017",
    },
    {
      key: "fashion-adidas-classic-3s-backpack",
      name: "کوله پشتی آدیداس Classic 3S",
      nameEn: "Adidas Classic 3S Backpack",
      price: 1950000,
      stock: 30,
      categorySlug: "bags",
      brandName: "آدیداس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e92a38b4bcde.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/fe1537ca6cd7.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ecf23cd92972.jpg",
      ],
      rating: 4.6,
      reviewCount: 117,
      soldCount: 280,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "پلی‌استر ریپ‌استاپ سبک" },
        { key: "سایزبندی", value: "ظرفیت ۲۶ لیتر" },
        { key: "رنگ", value: "مشکی / آبی Black-Blue" },
        { key: "کاربرد", value: "دانشگاهی، شهری و روزمره" },
        { key: "ویژگی", value: "جیب لپ‌تاپ ۱۵ اینچ + آستر ضد آب" },
      ],
      description:
        "کوله کلاسیک ۳S آدیداس با ۲۶ لیتر ظرفیت و جیب مخصوص لپ‌تاپ ۱۵ اینچی، کوله روزمره‌ی اسپرت است. دو جیب کناری مش برای بطری آب و سه نوار آدیداس روی جلو آن را از هر کولوی دیگری متمایز می‌کند.",
      sku: "FAS-BAG-018",
    },

    /* ── لباس راحتی ────────────────────────────────────────────────── */
    {
      key: "fashion-puma-essential-lounge-set",
      name: "ست لباس راحتی پما Essential زنانه",
      nameEn: "Puma Essential Women's Loungewear Set",
      price: 2250000,
      discountPrice: 1850000,
      stock: 17,
      categorySlug: "loungewear",
      brandName: "پما",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/21c090077e9e.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/1bf6d3bbf455.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4b33796de7e8.jpg",
      ],
      rating: 4.4,
      reviewCount: 68,
      soldCount: 195,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "جنس", value: "پنبه فلامه نرم ۶۸٪ / پلی‌استر" },
        { key: "سایزبندی", value: "XS تا XL (تاپ + شلوار)" },
        { key: "رنگ", value: "صورتی / سبز کاکتوس" },
        { key: "کاربرد", value: "خانه، ریکاوری و استایل استریت" },
        { key: "ویژگی", value: "کش پهن مچ + لمس ضد آبرفت" },
      ],
      description:
        "ست راحتی پما شامل تاپ و شلوار جوگری فلامه است که از صبح خانه تا قهوه با دوستان، یک استایل اسپرت-راحتی کامل می‌سازد. پنبه اشباع‌شده آن بعد از شست‌وشو جمع نمی‌شود و لطافتش را نگه می‌دارد.",
      sku: "FAS-LOU-019",
    },
    {
      key: "fashion-newbalance-essential-joggers",
      name: "شلوار راحتی نیوبالانس Essential زنانه",
      nameEn: "New Balance Women's Essential Joggers",
      price: 1690000,
      stock: 27,
      categorySlug: "loungewear",
      brandName: "نیوبالانس",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/324ff05b83a4.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/105fb1205162.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/50642abf6adf.jpg",
      ],
      rating: 4.3,
      reviewCount: 45,
      soldCount: 240,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "جنس", value: "فلامه نرم پنبه مخلوط" },
        { key: "سایزبندی", value: "XS تا XL" },
        { key: "رنگ", value: "خاکستری Heath / مشکی" },
        { key: "کاربرد", value: "دویدن سبک، خانه و استایل روزمره" },
        { key: "ویژگی", value: "کمر کشی + جیب‌های جانبی عمیق" },
      ],
      description:
        "شلوار جوگری نیوبالانس با کمر کشی نرم و پاچین مچ‌دار، بین تمرین سبک و استراحت خانه مرزی قائل نیست. فلامه سبکش برای فصول میانه عالی است و با هر هودی ساده یک استایل استریت‌ور مرتب می‌سازد.",
      sku: "FAS-LOU-020",
    },
  ],
};
