/**
 * v35 · VERTICAL CATALOG — «آرایشی و بهداشتی» (Beauty & Care)
 * ------------------------------------------------------------------
 * PURE DATA (no imports besides the contract types). The complete beauty
 * vertical: 9 categories, 8 brands and 20 REAL products (Persian names,
 * تومان prices, discounts, stock, 4–6 Persian specs, marketing copy and
 * stable OSS images picked from image-search). Consumed by the vertical
 * switch API (reseed) + the AI persona and rendered by the storefront
 * template "beauty-glow" (src/components/store/templates/beauty-glow.tsx).
 */

import type { VerticalDef } from "./types";

export const BEAUTY_CATALOG: VerticalDef = {
  id: "beauty",
  nameFa: "آرایشی و بهداشتی",
  nameEn: "Beauty & Care",
  templateId: "beauty-glow",
  taglineFa: "زیبایی و مراقبت پوست",
  descFa:
    "فروشگاه تخصصی محصولات آرایشی و بهداشتی اصل — از سرم‌های مراقبت پوست و ضدآفتاب تا آرایش چشم و لب، عطر و ست‌های هدیه با برندهای معتبر جهانی.",
  icon: "Sparkles",

  aiPersona:
    "تو مشاور زیبایی و کارشناس مراقبت پوست این فروشگاه هستی و مثل یک خواهر مهربان و صمیمی همراه کاربر حرف می‌زنی. بر اساس نوع پوست او (چرب، خشک یا مختلط) یک روتین پاکسازی، آبرسانی و ضدآفتاز ساده و قابل اجرا پیشنهاد بده و در انتخاب سرم، کرم، ضدآفتاب و آرایش صورت حتماً محصولات همین فروشگاه را معرفی کن. درباره ترکیباتی مثل هیالورونیک اسید، نیاسینامید و ویتامین C با زبان ساده و درست توضیح بده و اگر سؤالی درباره آرایش لب و چشم، عطر مناسب یا مراقبت مو و بدن بود با لحنی گرم و دلگرم‌کننده پاسخ بده. اگر کاربر مشکل بیماری پوستی مثل آکنز شدید، حساسیت، قارچ یا زخم مطرح کرد، هیچ تشخیص یا نسخه پزشکی نده و مؤدبانه او را به متخصص پوست ارجاع بده. به سؤال‌های بی‌ربط به حوزه زیبایی و مراقبت هم کوتاه و محترمانه جواب نده و فقط در حوزه تخصصی خودت راهنمایی کن.",

  categories: [
    { name: "مراقبت پوست", slug: "skincare", icon: "Droplets", description: "سرم، تونر، شوینده و آبرسان برای همه انواع پوست", sortOrder: 1 },
    { name: "آردر و کرم", slug: "creams", icon: "Flower2", description: "کرم‌های مرطوب‌کننده، آبرسان و ترمیمی روتین روزانه", sortOrder: 2 },
    { name: "ضدآفتاب", slug: "sunscreen", icon: "Sun", description: "محافظت روزانه پوست با SPFهای متناسب پوست ایران", sortOrder: 3 },
    { name: "آرایش صورت", slug: "face-makeup", icon: "Palette", description: "کرم پودر، برنزر و پالت سایه برای یک makeup ملایم", sortOrder: 4 },
    { name: "آرایش لب و چشم", slug: "lip-eye-makeup", icon: "Smile", description: "ماسکارا، مداد ابرو، رژ و برق لب ماندگار", sortOrder: 5 },
    { name: "عطر و ادکلن", slug: "fragrance", icon: "SprayCan", description: "ادوپرفیوم و اسپری بدن با رایحه‌های ماندگار", sortOrder: 6 },
    { name: "مراقبت مو", slug: "haircare", icon: "Scissors", description: "شامپو و ماسک تقویت‌کننده برای موهای خسته", sortOrder: 7 },
    { name: "بهداشت بدن", slug: "bodycare", icon: "Bath", description: "دئودورانت و لوسیون‌های ملایم مراقبت بدن", sortOrder: 8 },
    { name: "ست‌های هدیه", slug: "gift-sets", icon: "Gift", description: "ست‌های کامل روتین و آرایش، آماده هدیه دادن", sortOrder: 9 },
  ],

  brands: [
    { name: "لورآل", slug: "loreal" },
    { name: "گارنیه", slug: "garnier" },
    { name: "سراوی", slug: "cerave" },
    { name: "نیوآ", slug: "nivea" },
    { name: "میبلین", slug: "maybelline" },
    { name: "بینفیت", slug: "benefit" },
    { name: "درماتیکا", slug: "dermatica" },
    { name: "اورآل", slug: "oreal" },
  ],

  products: [
    /* ── مراقبت پوست ─────────────────────────────────────────────── */
    {
      key: "cerave-serum-vitc",
      name: "سرم ویتامین C سراوی با غلظت ۱۵٪ حجم ۳۰ میلی‌لیتر",
      nameEn: "CeraVe Skin Renewing Vitamin C Serum 30ml",
      price: 1890000,
      discountPrice: 1590000,
      stock: 24,
      categorySlug: "skincare",
      brandName: "سراوی",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/461736cce1ce.png",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/222125ea47ae.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b10c72df8185.jpg",
      ],
      rating: 4.7,
      reviewCount: 312,
      soldCount: 890,
      featured: true,
      isSpecial: true,
      specs: [
        { key: "حجم", value: "۳۰ میلی‌لیتر" },
        { key: "نوع پوست", value: "همه انواع پوست" },
        { key: "نوع محصول", value: "سرم روشن‌کننده" },
        { key: "ترکیبات", value: "ویتامین C ۱۵٪، اسید فرولیک، سرامید" },
        { key: "زمان مصرف", value: "صبح‌ها بعد از پاکسازی" },
      ],
      description:
        "سرم روشن‌کننده سراوی با ویتامین C پایدار و سه سرامید Essential، لک و تیرگی‌های پوست را کم می‌کند و بافتی شفاف‌تر و یکدست می‌سازد. فرمول سبک و بدون چربی آن برای استفاده روزانه زیر کرم و ضدآفتاب کاملاً مناسب است.",
      sku: "BTY-SKN-001",
    },
    {
      key: "cerave-foam-cleanser",
      name: "فوم شوینده سراوی مناسب پوست چرب و مستعد آکنه حجم ۲۳۷ میلی‌لیتر",
      nameEn: "CeraVe Foaming Facial Cleanser 237ml",
      price: 690000,
      discountPrice: null,
      stock: 38,
      categorySlug: "skincare",
      brandName: "سراوی",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f038e12fbe52.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5d4ad3ed889b.png",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/bcb57646f1f8.jpg",
      ],
      rating: 4.8,
      reviewCount: 248,
      soldCount: 1150,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۲۳۷ میلی‌لیتر" },
        { key: "نوع پوست", value: "چرب و مختلط" },
        { key: "نوع محصول", value: "فوم شوینده صورت" },
        { key: "ترکیبات", value: "سرامید، نیاسینامید، بدون سولفات" },
        { key: "ساخت", value: "آمریکا" },
      ],
      description:
        "فوم بدون سولفات سراوی چربی اضافه و آلودگی پوست چرب را به‌خوبی می‌شوید بدون آنکه سد دفاعی پوست آسیب ببیند. نیاسینامید موجود در فرمول، التهاب و قرمزی پوست‌های مستعد آکنه را آرام نگه می‌دارد.",
      sku: "BTY-SKN-002",
    },
    {
      key: "garnier-micellar-oily",
      name: "آب میسلار گارنیه پاک‌کننده آرایش پوست چرب حجم ۴۰۰ میلی‌لیتر",
      nameEn: "Garnier Micellar Cleansing Water Oily Skin 400ml",
      price: 445000,
      discountPrice: 369000,
      stock: 40,
      categorySlug: "skincare",
      brandName: "گارنیه",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c3684feb82cb.jpeg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5706918a748e.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e89888784111.jpg",
      ],
      rating: 4.6,
      reviewCount: 410,
      soldCount: 2400,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۴۰۰ میلی‌لیتر" },
        { key: "نوع پوست", value: "چرب و مختلط" },
        { key: "نوع محصول", value: "آب میسلار" },
        { key: "ترکیبات", value: "میسل‌های پاک‌کننده، بدون الکل" },
        { key: "ویژگی", value: "بدون نیاز به آبکشی" },
      ],
      description:
        "آب میسلار گارنیه آرایش صورت و آلودگی روزانه را در یک قدم و بدون سابقه ملایم پاک می‌کند. فرمول مخصوص پوست چرب براقی اضافه را کنترل می‌کند و حس تازگی بعد از استفاده باقی می‌ماند.",
      sku: "BTY-SKN-003",
    },
    {
      key: "loreal-revitalift-hyal",
      name: "سرم هیالورونیک اسید لورآل ریویتالفت حجم ۳۰ میلی‌لیتر",
      nameEn: "L'Oréal Revitalift Hyaluronic Acid Serum 30ml",
      price: 1150000,
      discountPrice: null,
      stock: 19,
      categorySlug: "skincare",
      brandName: "لورآل",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/42a141fc5b25.jpeg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d9d88f72f908.png",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/41b33202c9d1.jpg",
      ],
      rating: 4.5,
      reviewCount: 187,
      soldCount: 640,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۳۰ میلی‌لیتر" },
        { key: "نوع پوست", value: "خشک و مختلط" },
        { key: "نوع محصول", value: "سرم آبرسان" },
        { key: "ترکیبات", value: "هیالورونیک اسید ۱.۵٪، ویتامین B5" },
      ],
      description:
        "سرم آبرسان لورآل با دو وزن مولکولی هیالورونیک اسید، رطوبت را در لایه‌های مختلف پوست نگه می‌دارد و خطوط ریز ناشی از خشکی را کم می‌کند. بافت سبک و سریع‌جذب آن زیر کرم شب یا روز بدون سنگینی استفاده می‌شود.",
      sku: "BTY-SKN-004",
    },

    /* ── آردر و کرم ───────────────────────────────────────────────── */
    {
      key: "dermatica-hyal-cream",
      name: "کرم آبرسان هیالورونیک درماتیکا حجم ۵۰ میلی‌لیتر",
      nameEn: "Dermatica Hyaluronic Moisturizing Cream 50ml",
      price: 760000,
      discountPrice: null,
      stock: 27,
      categorySlug: "creams",
      brandName: "درماتیکا",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/a2d88cff323b.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/60a56d494f24.webp",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7eb558b1fa6f.jpg",
      ],
      rating: 4.4,
      reviewCount: 96,
      soldCount: 310,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۵۰ میلی‌لیتر" },
        { key: "نوع پوست", value: "خشک و حساس" },
        { key: "نوع محصول", value: "کرم آبرسان" },
        { key: "ترکیبات", value: "هیالورونیک اسید، گلیسیرین، پانتنول" },
        { key: "زمان مصرف", value: "صبح و شب" },
      ],
      description:
        "کرم آبرسان درماتیکا با هیالورونیک اسید و پانتنول، خشکی و کشیدگی پوست را در طول روز رفع می‌کند. بافت متوسط آن مناسب پوست‌های حساس است و زیر آرایش هم حالت کیک‌ای ایجاد نمی‌کند.",
      sku: "BTY-CRM-001",
    },
    {
      key: "nivea-soft-cream",
      name: "کرم چندکاره نیوآ سافت حجم ۲۰۰ میلی‌لیتر",
      nameEn: "Nivea Soft Moisturizing Cream 200ml",
      price: 385000,
      discountPrice: 315000,
      stock: 35,
      categorySlug: "creams",
      brandName: "نیوآ",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/740960bcc503.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ebfe159c5fc9.jpeg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/519b08930a4e.jpg",
      ],
      rating: 4.6,
      reviewCount: 205,
      soldCount: 1900,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۲۰۰ میلی‌لیتر" },
        { key: "نوع پوست", value: "همه انواع پوست" },
        { key: "نوع محصول", value: "کرم مرطوب‌کننده" },
        { key: "ترکیبات", value: "روغن جوجوبا، ویتامین E" },
        { key: "کاربرد", value: "صورت، دست و بدن" },
      ],
      description:
        "کرم کلاسیک نیوآ سافت با روغن جوجوبا و ویتامین E، سریع جذب می‌شود و پوست صورت، دست و بدن را نرم و مرطوب نگه می‌دارد. انتخاب اقتصادی و مطمئن برای مصرف روزانه کل خانواده است.",
      sku: "BTY-CRM-002",
    },

    /* ── ضدآفتاب ─────────────────────────────────────────────────── */
    {
      key: "loreal-uv-perfect",
      name: "کرم ضدآفتاب لورآل یووی پرفکت SPF50 حجم ۵۰ میلی‌لیتر",
      nameEn: "L'Oréal UV Perfect SPF50 Sunscreen 50ml",
      price: 1180000,
      discountPrice: null,
      stock: 22,
      categorySlug: "sunscreen",
      brandName: "لورآل",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/30dbf36f9c48.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9db3ee8c18c4.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/a67fc8ff30fa.jpg",
      ],
      rating: 4.5,
      reviewCount: 154,
      soldCount: 520,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۵۰ میلی‌لیتر" },
        { key: "نوع پوست", value: "همه انواع پوست" },
        { key: "نوع محصول", value: "کرم ضدآفتاب روزانه" },
        { key: "درجه حفاظت", value: "SPF50 / PA+++" },
        { key: "ترکیبات", value: "فیلترهای مینرال و شیمیایی" },
      ],
      description:
        "ضدآفتاب بی‌رنگ لورآل با SPF50 از پوست در برابر آفتاب شدید روزهای ایرانی محافظت می‌کند و از ایجاد لک و تیرگی جلوگیری می‌کند. بافت سبک آن زیر آرایش حالت سنگین ایجاد نمی‌کند و روبه‌روی نور هم سفیدی ندارد.",
      sku: "BTY-SUN-001",
    },
    {
      key: "garnier-ambre-solaire",
      name: "اسپری ضدآفتاب گارنیه آمبره سولر SPF50 حجم ۲۰۰ میلی‌لیتر",
      nameEn: "Garnier Ambre Solaire SPF50 Sunscreen Spray 200ml",
      price: 890000,
      discountPrice: 745000,
      stock: 16,
      categorySlug: "sunscreen",
      brandName: "گارنیه",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f4243385b438.jpeg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/0e27e4a126c7.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/23cf7662f8d5.jpg",
      ],
      rating: 4.4,
      reviewCount: 138,
      soldCount: 480,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "حجم", value: "۲۰۰ میلی‌لیتر" },
        { key: "نوع پوست", value: "همه انواع پوست" },
        { key: "نوع محصول", value: "اسپری ضدآفتاب" },
        { key: "درجه حفاظت", value: "SPF50" },
        { key: "ویژگی", value: "آب‌بند و ضد تعریق" },
      ],
      description:
        "اسپری ضدآفتاب گارنیه به‌سادگی و یکنواخت روی پوست صورت و بدن اسپری می‌شود و برای روزهای پرتحرک و سفر عالی است. فرمول آب‌بند آن در برابر تعریق و شنا هم ماندگار می‌ماند.",
      sku: "BTY-SUN-002",
    },

    /* ── آرایش صورت ───────────────────────────────────────────────── */
    {
      key: "maybelline-superstay-foundation",
      name: "کرم پودر مات میبلین سوپراستی پوشش ۲۴ ساعته شماره ۳۰",
      nameEn: "Maybelline SuperStay 24H Matte Foundation 30",
      price: 940000,
      discountPrice: 790000,
      stock: 18,
      categorySlug: "face-makeup",
      brandName: "میبلین",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2f0a01847ef6.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8be1f6abb682.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/3b80c490a0a9.webp",
      ],
      rating: 4.6,
      reviewCount: 226,
      soldCount: 1300,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "سایز", value: "۳۰ میلی‌لیتر" },
        { key: "سایه", value: "شماره ۳۰ (سفید مایل به زرد)" },
        { key: "نوع محصول", value: "کرم پودر مات" },
        { key: "پوشش", value: "کامل و ۲۴ ساعته" },
        { key: "نتیجه", value: "مات بدون اثر ماسکی" },
      ],
      description:
        "کرم پودر سوپراستی میبلین تا ۲۴ ساعت پوشش کامل و مات بدون اثر سنگین نگه می‌دارد و برای روزهای شلوغ و گرما انتخاب مطمئنی است. شماره ۳۰ با پوست‌های روشن ایرانی هماهنگی خوبی دارد.",
      sku: "BTY-FCE-001",
    },
    {
      key: "oreal-nude-palette",
      name: "پالت سایه چشم اورآل تن‌های نود ۱۲ رنگ",
      nameEn: "Oreal Nude Eyeshadow Palette 12 Shades",
      price: 1250000,
      discountPrice: null,
      stock: 12,
      categorySlug: "face-makeup",
      brandName: "اورآل",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/1cbb9eb94eb3.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/96a2a0e19a3d.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b3a1682de3af.png",
      ],
      rating: 4.3,
      reviewCount: 87,
      soldCount: 290,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "تعداد سایه", value: "۱۲ رنگ" },
        { key: "تناژ", value: "نود و خاکی ملایم" },
        { key: "نوع محصول", value: "پالت سایه چشم" },
        { key: "پرداخت", value: "مات، ساتن و شاتیم" },
      ],
      description:
        "پالت نود اورآل با ترکیبی از رنگ‌های مات و براق، هم برای گریم روزانه ملایم و هم آرایش شب مناسب است. پیگمنت ملایم و پخش‌شدن آسان رنگ‌ها، بلند کردن آن را حتی برای مبتدی‌ها ساده می‌کند.",
      sku: "BTY-FCE-002",
    },
    {
      key: "benefit-hoola-bronzer",
      name: "پودر برنزر بینفیت هولا حجم ۸ گرم",
      nameEn: "Benefit Hoola Matte Bronzer 8g",
      price: 2450000,
      discountPrice: null,
      stock: 8,
      categorySlug: "face-makeup",
      brandName: "بینفیت",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/998af28b4868.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/fe462c830448.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e335fe1604bb.jpg",
      ],
      rating: 4.8,
      reviewCount: 176,
      soldCount: 410,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "حجم", value: "۸ گرم" },
        { key: "تناژ", value: "قهوه‌ای خاکی مات" },
        { key: "نوع محصول", value: "پودر برنزر و کانتور" },
        { key: "پوشش", value: "قابل ساخت با پن براش" },
      ],
      description:
        "برنزر افسانه‌ای هولا با رنگ خاکی مات، صورت را فرم می‌دهد و بدون هیچ رد نارنجی، برنزه‌ای طبیعی می‌سازد. بافر یک‌سره داخل جعبه، به‌عنوان کانتور ظریف روی استخوان گونه کاربرد دارد.",
      sku: "BTY-FCE-003",
    },

    /* ── آرایش لب و چشم ───────────────────────────────────────────── */
    {
      key: "maybelline-sky-high-mascara",
      name: "ماسکارا حجم‌دهنده و طول‌دهنده میبلین اسکای های واترپروف",
      nameEn: "Maybelline Sky High Waterproof Mascara",
      price: 620000,
      discountPrice: null,
      stock: 30,
      categorySlug: "lip-eye-makeup",
      brandName: "میبلین",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9d037862f2e3.jpeg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c84ea0204aba.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f8a541887d87.jpg",
      ],
      rating: 4.7,
      reviewCount: 289,
      soldCount: 2100,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "نوع محصول", value: "ماسکارا واترپروف" },
        { key: "نتیجه", value: "طول و حجم مژه" },
        { key: "براش", value: "کلاهک مخملی انعطاف‌پذیر" },
        { key: "ترکیبات", value: "عصره بامبو و ویتامین E" },
      ],
      description:
        "ماسکارا اسکای های مژه‌های کوتاه را کشیده و پرپشت نشان می‌دهد و فرمول واترپروف آن تا آخر شب پلک نمی‌زند. براش مخملی، رد پای ماسکارا روی پلک نمی‌گذارد و مژه‌های پایینی هم رنگ می‌گیرند.",
      sku: "BTY-LIP-001",
    },
    {
      key: "maybelline-lifter-gloss",
      name: "برق لب میبلین لیفر گلاس با هیالورونیک شماره ۲۳",
      nameEn: "Maybelline Lifter Gloss 09 Honey",
      price: 545000,
      discountPrice: 465000,
      stock: 26,
      categorySlug: "lip-eye-makeup",
      brandName: "میبلین",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6b8cd6176432.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/0f23e8758fb4.jpeg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b1193ca1fe1c.jpg",
      ],
      rating: 4.5,
      reviewCount: 158,
      soldCount: 760,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "سایه", value: "شماره ۲۳ هانی" },
        { key: "نوع محصول", value: "برق لب حجم‌دهنده" },
        { key: "ترکیبات", value: "هیالورونیک اسید، روغن آرگان" },
        { key: "نتیجه", value: "براق با حس حجم" },
      ],
      description:
        "برق لب لیفر گلاس با هیالورونیک و روغن آرگان، لب‌ها را براق و پرحجم نشان می‌دهد و خشکی لب را هم جبران می‌کند. رنگ هانی نود، با هر لُک آرایشی هارمونی می‌سازد.",
      sku: "BTY-LIP-002",
    },
    {
      key: "benefit-precisely-brow",
      name: "مداد ابرو ضدآب بینفیت پرایسلی مای برو شماره ۳ متوسط",
      nameEn: "Benefit Precisely My Brow Pencil 3.5 Medium",
      price: 1350000,
      discountPrice: null,
      stock: 0,
      categorySlug: "lip-eye-makeup",
      brandName: "بینفیت",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4c7dc65b8408.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/1b6aaf26a567.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/1d40182fba27.jpg",
      ],
      rating: 4.6,
      reviewCount: 121,
      soldCount: 380,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "سایه", value: "شماره ۳ (متوسط)" },
        { key: "نوع محصول", value: "مداد ابرو ضدآب" },
        { key: "قابلیت", value: "نوک باریک ۱.۵ میلی‌متری" },
        { key: "ماندگاری", value: "تا ۱۲ ساعت" },
      ],
      description:
        "مداد ابروی بینفیت با نوک فوق‌باریک، تار به تار ابرو را فرم می‌دهد و نتیجه‌ای طبیعی می‌سازد. فرمول ضدآب آن در گرما و رطوبت پاک نمی‌شود و تا آخر روز سر جایش می‌ماند.",
      sku: "BTY-LIP-003",
    },

    /* ── عطر و ادکلن ──────────────────────────────────────────────── */
    {
      key: "oreal-blossom-edp",
      name: "ادوپرفیوم زنانه اورآل بلوسم حجم ۱۰۰ میلی‌لیتر",
      nameEn: "Oreal Blossom Eau de Parfum 100ml",
      price: 2350000,
      discountPrice: 1980000,
      stock: 10,
      categorySlug: "fragrance",
      brandName: "اورآل",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7e255961546f.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/3a8cd2983133.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4038274260e3.jpeg",
      ],
      rating: 4.5,
      reviewCount: 143,
      soldCount: 350,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "حجم", value: "۱۰۰ میلی‌لیتر" },
        { key: "غلظت", value: "ادوپرفیوم (EDP)" },
        { key: "رایحه", value: "گلی - میوه‌ای شیرین" },
        { key: "نت‌ها", value: "شکوفه گیلاس، یاس، مشک" },
        { key: "ماندگاری", value: "۶ تا ۸ ساعت" },
      ],
      description:
        "ادوپرفیوم بلوسم با نت شکوفه گیلاس و یاس، رایحه‌ای دخترانه و بهاری دارد که در هوای گرم هم تلخ نمی‌شود. رائحة مشک پایه، ماندگاری ملایم و شیکی به آن می‌دهد که برای استفاده روزانه عالی است.",
      sku: "BTY-PRF-001",
    },
    {
      key: "loreal-men-body-spray",
      name: "اسپری بدن مردانه لورآل من اکسپرت حجم ۲۵۰ میلی‌لیتر",
      nameEn: "L'Oréal Men Expert Body Spray 250ml",
      price: 465000,
      discountPrice: null,
      stock: 28,
      categorySlug: "fragrance",
      brandName: "لورآل",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/313cc159abf2.jpeg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e3cfb6690872.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/60129d66b41e.jpg",
      ],
      rating: 4.2,
      reviewCount: 64,
      soldCount: 940,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۲۵۰ میلی‌لیتر" },
        { key: "جنس", value: "مردانه" },
        { key: "نوع محصول", value: "اسپری بدن و دئودورانت" },
        { key: "رایحه", value: "خنک - چوبی" },
        { key: "ویژگی", value: "کنترل بوی تعریق" },
      ],
      description:
        "اسپری بدن من اکسپرت با رایحه خنک و چوبی، بوی تعریق را کنترل می‌کند و طول روز حس تازگی می‌دهد. حجم بزرگ آن برای استفاده روزانه ورزشی و محل کار کاملاً به‌صرفه است.",
      sku: "BTY-PRF-002",
    },

    /* ── مراقبت مو ────────────────────────────────────────────────── */
    {
      key: "garnier-fructis-shampoo",
      name: "شامپو گارنیه فراکتس مخصوص موهای بلند و خسته حجم ۴۰۰ میلی‌لیتر",
      nameEn: "Garnier Fructis Long & Strong Shampoo 400ml",
      price: 395000,
      discountPrice: null,
      stock: 32,
      categorySlug: "haircare",
      brandName: "گارنیه",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9701ba609bb8.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d8fa84a1c601.png",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7bb681391fc8.jpg",
      ],
      rating: 4.5,
      reviewCount: 198,
      soldCount: 1600,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۴۰۰ میلی‌لیتر" },
        { key: "نوع مو", value: "بلند و آسیب‌دیده" },
        { key: "نوع محصول", value: "شامپو تقویت‌کننده" },
        { key: "ترکیبات", value: "عصره میوه، بیوتین، بدون سیلیکون سنگین" },
      ],
      description:
        "شامپو فراکتس گارنیه موهای بلند را از ریشه تقویت می‌کند و موخوره و شکستگی ساقه مو را کاهش می‌دهد. فرمول بدون سیلیکون سنگین، مو را سبک و براق نگه می‌دارد بدون سنگین‌کردن ریشه.",
      sku: "BTY-HAR-001",
    },
    {
      key: "loreal-elseve-hair-mask",
      name: "ماسک مغذی مو لورآل الویو حجم ۳۰۰ میلی‌لیتر",
      nameEn: "L'Oréal Elseve Nourishing Hair Mask 300ml",
      price: 675000,
      discountPrice: null,
      stock: 15,
      categorySlug: "haircare",
      brandName: "لورآل",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8b774964d2a7.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2e104001dfec.jpeg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/941f266f6331.jpg",
      ],
      rating: 4.4,
      reviewCount: 92,
      soldCount: 260,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۳۰۰ میلی‌لیتر" },
        { key: "نوع مو", value: "خشک و رنگ‌شده" },
        { key: "نوع محصول", value: "ماسک مو" },
        { key: "ترکیبات", value: "روغن آرگان، روغن گل سرخ، پروتین گندم" },
      ],
      description:
        "ماسک الویو با روغن‌های مغذی، موهای خشک و رنگ‌شده را در ۳ تا ۵ دقیقه نرم و شانه‌پذیر می‌کند و وز کلی مو را از بین می‌برد. استفاده هفته‌ای دو بار برای موهای آسیب‌دیده نتیجه محسوسی می‌دهد.",
      sku: "BTY-HAR-002",
    },

    /* ── بهداشت بدن ───────────────────────────────────────────────── */
    {
      key: "nivea-cool-roll",
      name: "دئودورانت رول خنک‌کننده نیوآ حجم ۵۰ میلی‌لیتر",
      nameEn: "Nivea Cool Kick Roll-on Deodorant 50ml",
      price: 285000,
      discountPrice: null,
      stock: 36,
      categorySlug: "bodycare",
      brandName: "نیوآ",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/40b45711ce12.jpg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/33984251ca2c.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/394a84d279a1.jpg",
      ],
      rating: 4.3,
      reviewCount: 175,
      soldCount: 2200,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حجم", value: "۵۰ میلی‌لیتر" },
        { key: "نوع محصول", value: "دئودورانت رول" },
        { key: "ترکیبات", value: "بدون الکل، خوش‌بوکننده ملایم" },
        { key: "ویژگی", value: "حس خنکی فوری، بدون لکه روی لباس" },
      ],
      description:
        "رول خنک‌کننده نیوآ بدون الکل بوی تعریق را ۴۸ ساعت کنترل می‌کند و روی پوست حساس زیر بغل هم ملایم است. بافت سریع‌خشک‌شونده آن رد سفید روی لباس تیره نمی‌گذارد.",
      sku: "BTY-BDY-001",
    },

    /* ── ست‌های هدیه ──────────────────────────────────────────────── */
    {
      key: "cerave-gift-set",
      name: "ست هدیه روتین پوست سراوی شامل فوم شوینده، سرم و کرم مرطوب‌کننده",
      nameEn: "CeraVe Skincare Routine Gift Set (3 pcs)",
      price: 3850000,
      discountPrice: 3290000,
      stock: 6,
      categorySlug: "gift-sets",
      brandName: "سراوی",
      image: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/a565bde6a160.jpeg",
      gallery: [
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b5e9e5c5abbb.jpg",
        "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4de55f897bc3.png",
      ],
      rating: 4.9,
      reviewCount: 64,
      soldCount: 120,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "تعداد اقلام", value: "۳ قلم" },
        { key: "مناسب برای", value: "همه انواع پوست" },
        { key: "نوع محصول", value: "ست روتین کامل" },
        { key: "اقلام", value: "فوم ۲۳۷ml، سرم ۳۰ml، کرم ۸۹ml" },
        { key: "بسته‌بندی", value: "جعبه هدیه سراوی" },
      ],
      description:
        "ست کامل روتین سراوی شامل فوم شوینده، سرم ویتامین C و کرم مرطوب‌کننده؛ یعنی پاکسازی، درمان و آبرسانی در یک جعبه شیک. انتخاب آماده و مطمئن برای هدیه به هر کسی که پوستش برایش مهم است.",
      sku: "BTY-GFT-001",
    },
  ],
};
