import type { VerticalDef, VerticalProductSeed } from "./types";

/**
 * v35 · GAMING VERTICAL — «گیمینگ حرفه‌ای»
 * --------------------------------------------------------------------
 * PURE DATA catalog for the gaming vertical (id: "gaming"). Activating
 * the vertical reseeds the store with a pro-gaming assortment — GPUs,
 * CPUs, motherboards/RAM, gaming laptops & monitors, cases/cooling,
 * controllers, chairs/desks and streaming gear — plus the AI persona
 * that answers in character (a gear-head coach) and the flagship
 * storefront template «zentry-gaming».
 *
 * All images are stable OSS urls (z-cdn.chatglm.cn) fetched via
 * z-ai image-search (one search per product, 2025-06 QA).
 * Prices are realistic Iranian-market numbers in تومان.
 */

/* ── stable OSS image urls (main + 1–2 gallery each) ─────────────── */
const IMG = {
  gpuAsus: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/77ede6f1c136.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/26b902f4a30d.png",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5db713ddb4c6.jpg",
    ],
  },
  gpuNvidia: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b7a87ec6cb14.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/50448a07ea44.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b2ef6f562ea2.jpg",
    ],
  },
  gpuMsi: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/3a8aa8bc724a.png",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cc661f670613.png",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/3c75a1b7939d.png",
    ],
  },
  cpuIntel: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/fdfb0805c978.png",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6e96c659e674.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d14c7dcae223.jpg",
    ],
  },
  cpuAmd: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d66236f5fcb1.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6e4b0fbe3f68.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/35bc3d26b7e4.png",
    ],
  },
  mbAsus: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f1563101cba9.png",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f0c72ec642aa.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c73786c8a2bf.jpg",
    ],
  },
  ramCorsair: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cd8eefd59da9.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/129a83eda39d.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/af6823aaa99a.jpg",
    ],
  },
  laptopRog: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2ff6c68059a1.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/a4266a4b94d4.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7664504679ff.jpg",
    ],
  },
  laptopMsi: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cbbe98e59dd7.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ffba9edf71d3.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f9a0ee0ba2bb.jpeg",
    ],
  },
  monMsi: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/bc96e6bd7ee0.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4f976dcc9cd0.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/726072c0aad8.jpg",
    ],
  },
  monRog: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c20d895cf452.png",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/fbe0109eb499.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ae4ce7ad6277.jpg",
    ],
  },
  caseCorsair: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/de7378e041fb.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2292069a6267.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5b9e7ce2d1a1.jpg",
    ],
  },
  coolMsi: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/7aab3721ec41.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/08cf62e3f5e3.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/68effc71d5c7.jpg",
    ],
  },
  conRazer: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6a29de3f18b7.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6ba981a24ae5.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/33395537b51f.jpg",
    ],
  },
  conRog: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/af1d9bd5729f.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/20f75a6cb266.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/51f6f3d2f5dd.jpg",
    ],
  },
  chairRazer: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/900d3baf4a1f.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/590f17833687.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b17e9e46a583.jpg",
    ],
  },
  deskCorsair: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/119bb752cbc3.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/0ee9215828d4.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f15e25641cb3.jpg",
    ],
  },
  hsSteel: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/b30c088df9bd.png",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/16207b81a05f.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/035dc4d48d78.jpg",
    ],
  },
  hsLogi: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c52dcd0a025f.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5bc0d12273b1.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e33d6550d9df.jpg",
    ],
  },
  micHyper: {
    main: "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/bfd0b555e9bc.jpg",
    gal: [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/79c11578e7cb.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4e4b15829ef5.jpg",
    ],
  },
} as const;

/* ── the 20 products (one z-ai image-search per product) ─────────── */
const PRODUCTS: VerticalProductSeed[] = [
  {
    key: "asus-rog-strix-rtx-4070-ti-super",
    name: "کارت گرافیک ASUS ROG Strix RTX 4070 Ti Super 16GB",
    nameEn: "ASUS ROG Strix GeForce RTX 4070 Ti Super OC 16GB",
    price: 82_500_000,
    stock: 6,
    categorySlug: "gpu",
    brandName: "ایسوس ROG",
    image: IMG.gpuAsus.main,
    gallery: [...IMG.gpuAsus.gal],
    rating: 4.7,
    reviewCount: 210,
    soldCount: 140,
    featured: true,
    sku: "GAM-GPU-001",
    specs: [
      { key: "حافظه", value: "16GB GDDR6X" },
      { key: "فرکانس بوست", value: "2.61GHz" },
      { key: "پورت‌ها", value: "HDMI 2.1 و 3× DisplayPort 1.4a" },
      { key: "پهنای باس", value: "256-bit" },
      { key: "توان مصرفی", value: "285 وات" },
      { key: "خنک‌کننده", value: "سه فان Axial-tech" },
    ],
    description:
      "کارت گرافیک پرچمدار سری Strix با خنک‌کننده سه‌فانه Axial-tech و بدنه متالیک؛ برای گیمینگ QHD و 4K با Ray Tracing کامل ساخته شده است. اورکلاک کارخانه‌ای و نور ARGB آن با مادربردهای سازگار همگام می‌شود.",
  },
  {
    key: "nvidia-rtx-4070-super-founders",
    name: "کارت گرافیک NVIDIA GeForce RTX 4070 Super Founders Edition 12GB",
    nameEn: "NVIDIA GeForce RTX 4070 Super Founders Edition 12GB",
    price: 61_900_000,
    discountPrice: 57_900_000,
    stock: 9,
    categorySlug: "gpu",
    brandName: "انویدیا",
    image: IMG.gpuNvidia.main,
    gallery: [...IMG.gpuNvidia.gal],
    rating: 4.6,
    reviewCount: 188,
    soldCount: 320,
    sku: "GAM-GPU-002",
    specs: [
      { key: "حافظه", value: "12GB GDDR6X" },
      { key: "فرکانس بوست", value: "2.48GHz" },
      { key: "هسته CUDA", value: "7168" },
      { key: "پورت‌ها", value: "HDMI 2.1 و 3× DisplayPort 1.4a" },
      { key: "توان مصرفی", value: "220 وات" },
      { key: "فناوری", value: "DLSS 3.5" },
    ],
    description:
      "نسخه رسمی Founders Edition انویدیا با کیفیت ساخت فلزی و طراحی دوقلویی فشرده؛ بهترین نسبت قیمت به کارایی برای گیمینگ 1440p. با DLSS 3.5 و Frame Generation فریم‌ریت بازی‌های سنگین چشمگیر بالا می‌رود.",
  },
  {
    key: "msi-rtx-4080-super-gaming-trio",
    name: "کارت گرافیک MSI Gaming Trio RTX 4080 Super 16GB",
    nameEn: "MSI Gaming Trio GeForce RTX 4080 Super 16GB",
    price: 118_500_000,
    stock: 3,
    categorySlug: "gpu",
    brandName: "ام اس آی",
    image: IMG.gpuMsi.main,
    gallery: [...IMG.gpuMsi.gal],
    rating: 4.8,
    reviewCount: 96,
    soldCount: 44,
    featured: true,
    isSpecial: true,
    sku: "GAM-GPU-003",
    specs: [
      { key: "حافظه", value: "16GB GDDR6X" },
      { key: "فرکانس بوست", value: "2.64GHz" },
      { key: "پورت‌ها", value: "HDMI 2.1 و 3× DisplayPort 1.4a" },
      { key: "فن", value: "3× TORX Fan 5.0" },
      { key: "توان مصرفی", value: "320 وات" },
      { key: "پشتوانه", value: "بک‌پلیت فلزی" },
    ],
    description:
      "هیولای گیمینگ 4K؛ RTX 4080 Super با خنک‌کننده TRI FROZR و فن‌های TORX 5.0 حتی زیر فشار کامل خنک و ساکت می‌ماند. برای استریم 4K و رندر ویدیو هم انتخاب استودیوهای حرفه‌ای است.",
  },
  {
    key: "intel-core-i7-14700k",
    name: "پردازنده Intel Core i7-14700K نسل چهاردهم",
    nameEn: "Intel Core i7-14700K",
    price: 24_900_000,
    stock: 12,
    categorySlug: "cpu",
    brandName: "اینتل",
    image: IMG.cpuIntel.main,
    gallery: [...IMG.cpuIntel.gal],
    rating: 4.6,
    reviewCount: 154,
    soldCount: 260,
    sku: "GAM-CPU-001",
    specs: [
      { key: "هسته / رشته", value: "20 هسته / 28 رشته" },
      { key: "فرکانس بوست", value: "5.4GHz" },
      { key: "حافظه کش", value: "33MB" },
      { key: "سوکت", value: "LGA1700" },
      { key: "رم پشتیبانی", value: "DDR5 و DDR4" },
      { key: "گرافیک مجتمع", value: "Intel UHD 770" },
    ],
    description:
      "پردازنده محبوب گیمرها و استریمرها؛ 20 هسته‌ی نسل 14 که گیم سنگین و استریم هم‌زمان را بدون افت فریم می‌کشد. برای رندر و ادیت ویدیو هم هم قدرتمند است و هم اقتصادی.",
  },
  {
    key: "amd-ryzen-7-7800x3d",
    name: "پردازنده AMD Ryzen 7 7800X3D با حافظه کش 3D V-Cache",
    nameEn: "AMD Ryzen 7 7800X3D",
    price: 22_400_000,
    discountPrice: 20_850_000,
    stock: 15,
    categorySlug: "cpu",
    brandName: "ای ام دی",
    image: IMG.cpuAmd.main,
    gallery: [...IMG.cpuAmd.gal],
    rating: 4.9,
    reviewCount: 285,
    soldCount: 410,
    featured: true,
    sku: "GAM-CPU-002",
    specs: [
      { key: "هسته / رشته", value: "8 هسته / 16 رشته" },
      { key: "فرکانس بوست", value: "5.0GHz" },
      { key: "حافظه کش", value: "104MB با 3D V-Cache" },
      { key: "سوکت", value: "AM5" },
      { key: "رم پشتیبانی", value: "DDR5" },
      { key: "توان مصرفی", value: "120 وات" },
    ],
    description:
      "پادشاه فریم‌ریت گیمینگ؛ حافظه کش سه‌لایه 3D V-Cache آن در بازی‌ها از پردازنده‌های گران‌تر هم جلو می‌زند. مصرف انرژی پایین و دمای معقول، آن را به بهترین انتخاب برای رگ گیمینگ تبدیل کرده است.",
  },
  {
    key: "asus-rog-strix-z790-e-gaming-wifi-2",
    name: "مادربرد ASUS ROG Strix Z790-E Gaming WiFi II",
    nameEn: "ASUS ROG Strix Z790-E Gaming WiFi II",
    price: 28_500_000,
    stock: 8,
    categorySlug: "motherboard-ram",
    brandName: "ایسوس ROG",
    image: IMG.mbAsus.main,
    gallery: [...IMG.mbAsus.gal],
    rating: 4.5,
    reviewCount: 74,
    soldCount: 58,
    sku: "GAM-MB-001",
    specs: [
      { key: "چیپست", value: "Intel Z790" },
      { key: "سوکت", value: "LGA1700" },
      { key: "رم", value: "4× DDR5 تا 192GB" },
      { key: "اسلات گرافیک", value: "3× PCIe 5.0" },
      { key: "شبکه", value: "WiFi 7 و LAN 2.5G" },
      { key: "اسلات SSD", value: "5× M.2" },
    ],
    description:
      "مادربرد پرچمدار ROG با طراحی سایبرپانکی و نور Diffused RGB؛ پایه ایده‌آل برای رگ نسل جدید اینتل است. WiFi 7 و پنج اسلات M.2 آن آینده‌نگری کامل برای آپگریدهای بعدی می‌دهد.",
  },
  {
    key: "corsair-vengeance-rgb-ddr5-32",
    name: "رم Corsair Vengeance RGB DDR5 ظرفیت 32GB (2×16) 6000MHz",
    nameEn: "Corsair Vengeance RGB DDR5 32GB (2×16) 6000MHz CL30",
    price: 9_450_000,
    discountPrice: 8_290_000,
    stock: 25,
    categorySlug: "motherboard-ram",
    brandName: "کورسیر",
    image: IMG.ramCorsair.main,
    gallery: [...IMG.ramCorsair.gal],
    rating: 4.7,
    reviewCount: 176,
    soldCount: 385,
    sku: "GAM-RAM-001",
    specs: [
      { key: "ظرفیت", value: "32GB (2×16GB)" },
      { key: "فرکانس", value: "6000MHz" },
      { key: "تایمینگ", value: "CL30" },
      { key: "ولتاژ", value: "1.35V" },
      { key: "نور", value: "ARGB قابل برنامه‌ریزی" },
      { key: "پروفایل", value: "XMP 3.0 و EXPO" },
    ],
    description:
      "رم استاندارد طلایی رگ‌های DDR5؛ ترکیب 6000MHz با CL30 دقیقاً نقطه شیرین پرفورمنس برای Ryzen 7000 و اینتل نسل 14 است. هیت‌اسپرد آلومینیومی و نور ARGB با نرم‌افزار iCUE هماهنگ می‌شود.",
  },
  {
    key: "asus-rog-strix-g16-rtx-4060",
    name: "لپ‌تاپ گیمینگ ASUS ROG Strix G16 با RTX 4060 و Core i9",
    nameEn: "ASUS ROG Strix G16 (RTX 4060 / Core i9)",
    price: 94_800_000,
    stock: 5,
    categorySlug: "gaming-laptop",
    brandName: "ایسوس ROG",
    image: IMG.laptopRog.main,
    gallery: [...IMG.laptopRog.gal],
    rating: 4.6,
    reviewCount: 128,
    soldCount: 86,
    featured: true,
    sku: "GAM-LAP-001",
    specs: [
      { key: "پردازنده", value: "Core i9-13980HX" },
      { key: "گرافیک", value: "RTX 4060 8GB" },
      { key: "نمایشگر", value: "16 اینچ QHD+ 165Hz" },
      { key: "رم", value: "16GB DDR5" },
      { key: "حافظه", value: "1TB NVMe SSD" },
      { key: "کیبورد", value: "نور Per-Key RGB" },
    ],
    description:
      "لپ‌تاپ گیمینگ 16 اینچی ROG با نمایشگر 165Hz و کیبورد تک‌کلیدی RGB؛ رگ قابل حمل برای ای‌اسپورت و رندر است. سیستم خنک‌کننده با خمیر ذخیره مایع، فریم‌ریت را زیر فشار سنگین پایدار نگه می‌دارد.",
  },
  {
    key: "msi-katana-15-rtx-4070",
    name: "لپ‌تاپ گیمینگ MSI Katana 15 با RTX 4070 و Core i7",
    nameEn: "MSI Katana 15 (RTX 4070 / Core i7)",
    price: 79_900_000,
    discountPrice: 74_500_000,
    stock: 7,
    categorySlug: "gaming-laptop",
    brandName: "ام اس آی",
    image: IMG.laptopMsi.main,
    gallery: [...IMG.laptopMsi.gal],
    rating: 4.4,
    reviewCount: 92,
    soldCount: 64,
    sku: "GAM-LAP-002",
    specs: [
      { key: "پردازنده", value: "Core i7-13620H" },
      { key: "گرافیک", value: "RTX 4070 8GB" },
      { key: "نمایشگر", value: "15.6 اینچ FHD 144Hz" },
      { key: "رم", value: "16GB DDR5" },
      { key: "حافظه", value: "1TB NVMe SSD" },
      { key: "خنک‌کننده", value: "Cooler Boost 5" },
    ],
    description:
      "بهترین نسبت قیمت به کارایی بین لپ‌تاپ‌های RTX 4070؛ Katana 15 با نمایشگر 144Hz برای گیمینگ رقابتی ساخته شده است. Cooler Boost 5 با دو فن و شش پایه حرارت را مهار می‌کند.",
  },
  {
    key: "msi-mag-274qrf-qd-e2",
    name: "مانیتور گیمینگ MSI MAG 274QRF QD E2 سایز 27 اینچ QHD 180Hz",
    nameEn: "MSI MAG 274QRF QD E2 27\" QHD 180Hz",
    price: 33_900_000,
    stock: 11,
    categorySlug: "gaming-monitor",
    brandName: "ام اس آی",
    image: IMG.monMsi.main,
    gallery: [...IMG.monMsi.gal],
    rating: 4.8,
    reviewCount: 232,
    soldCount: 190,
    featured: true,
    sku: "GAM-MON-001",
    specs: [
      { key: "رزولوشن", value: "QHD 2560×1440" },
      { key: "نرخ نوسازی", value: "180Hz" },
      { key: "پنل", value: "Rapid IPS با 1ms" },
      { key: "پورت‌ها", value: "HDMI 2.0 و DisplayPort 1.4" },
      { key: "پوشش رنگی", value: "Quantum Dot / 97% DCI-P3" },
      { key: "همگام‌سازی", value: "G-Sync Compatible" },
    ],
    description:
      "مانیتور محبوب گیمرهای FPS؛ پنل Rapid IPS با پاسخ 1ms و نرخ 180Hz بدون اسمیر، هدف‌گیری را دقیق‌تر می‌کند. فناوری Quantum Dot رنگ‌های زنده‌تر و کنتراست عمیق‌تری می‌سازد.",
  },
  {
    key: "asus-rog-swift-pg32uq",
    name: "مانیتور گیمینگ ASUS ROG Swift PG32UQ سایز 32 اینچ 4K 144Hz",
    nameEn: "ASUS ROG Swift PG32UQ 32\" 4K 144Hz",
    price: 98_500_000,
    discountPrice: 91_900_000,
    stock: 2,
    categorySlug: "gaming-monitor",
    brandName: "ایسوس ROG",
    image: IMG.monRog.main,
    gallery: [...IMG.monRog.gal],
    rating: 4.7,
    reviewCount: 88,
    soldCount: 31,
    isSpecial: true,
    sku: "GAM-MON-002",
    specs: [
      { key: "رزولوشن", value: "4K UHD 3840×2160" },
      { key: "نرخ نوسازی", value: "144Hz" },
      { key: "پنل", value: "IPS با 1ms" },
      { key: "پورت‌ها", value: "HDMI 2.1 و DisplayPort 1.4" },
      { key: "HDR", value: "DisplayHDR 600" },
      { key: "همگام‌سازی", value: "G-Sync Compatible" },
    ],
    description:
      "پرچمدار ROG Swift برای گیمینگ 4K واقعی؛ HDMI 2.1 آن با کنسول‌های نسل جدید هم کامل جور است. درخشش HDR 600 و رنگ‌های دقیق، آن را به مانیتور مشترک بازی و ساخت محتوا تبدیل کرده است.",
  },
  {
    key: "corsair-icue-5000x-rgb",
    name: "کیس گیمینگ Corsair iCUE 5000X RGB Mid Tower",
    nameEn: "Corsair iCUE 5000X RGB Mid-Tower",
    price: 14_300_000,
    stock: 10,
    categorySlug: "case-cooling",
    brandName: "کورسیر",
    image: IMG.caseCorsair.main,
    gallery: [...IMG.caseCorsair.gal],
    rating: 4.5,
    reviewCount: 145,
    soldCount: 210,
    sku: "GAM-CASE-001",
    specs: [
      { key: "فرم فاکتور", value: "Mid Tower" },
      { key: "پنل", value: "شیشه تمپرد" },
      { key: "فن", value: "3× RGB 120mm" },
      { key: "مادربرد", value: "تا E-ATX" },
      { key: "سازگاری AIO", value: "رادیاتور تا 360mm" },
      { key: "فضای گرافیک", value: "تا 360mm" },
    ],
    description:
      "کیس شیشه‌ای کورسیر با سه فن RGB و جریان هوای بالا؛ ویترین مهیای رگ شماست. سازگاری کامل با رادیاتور 360 و فضای کابل‌کشی تمیز، تجربه سوار کردن قطعات را لذت‌بخش می‌کند.",
  },
  {
    key: "msi-mag-coreliquid-a15-360",
    name: "خنک‌کننده مایع MSI MAG CoreLiquid A15 رادیاتور 360",
    nameEn: "MSI MAG CoreLiquid A15 360mm AIO",
    price: 8_900_000,
    stock: 14,
    categorySlug: "case-cooling",
    brandName: "ام اس آی",
    image: IMG.coolMsi.main,
    gallery: [...IMG.coolMsi.gal],
    rating: 4.4,
    reviewCount: 67,
    soldCount: 95,
    sku: "GAM-COOL-001",
    specs: [
      { key: "رادیاتور", value: "360mm" },
      { key: "فن", value: "3× 120mm ARGB" },
      { key: "پمپ", value: "پره‌های مارپیچی بهبودیافته" },
      { key: "سوکت‌ها", value: "LGA1700 و AM5" },
      { key: "نور", value: "ARGB" },
      { key: "گارانتی", value: "۵ سال" },
    ],
    description:
      "خنک‌کننده مایع 360 میلی‌متری با پمپ بهبودیافته و کارایی خنک‌کنندگی بالا برای پردازنده‌های پرقدرت. نور ARGB فن‌ها با مادربردهای MSI همگام می‌شود و رگ را حرفه‌ای نشان می‌دهد.",
  },
  {
    key: "razer-wolverine-v2-pro",
    name: "دسته بازی Razer Wolverine V2 Pro بی‌سیم",
    nameEn: "Razer Wolverine V2 Pro Wireless Controller",
    price: 6_750_000,
    discountPrice: 6_190_000,
    stock: 18,
    categorySlug: "console-controller",
    brandName: "ریزر",
    image: IMG.conRazer.main,
    gallery: [...IMG.conRazer.gal],
    rating: 4.6,
    reviewCount: 141,
    soldCount: 260,
    sku: "GAM-CON-001",
    specs: [
      { key: "اتصال", value: "بلوتوث و 2.4GHz" },
      { key: "سازگاری", value: "PS5، PS4 و PC" },
      { key: "دکمه‌ها", value: "Mecha-Tactile" },
      { key: "تریگر", value: "آنالوگ Hall Effect" },
      { key: "باتری", value: "تا ۱۰۰ ساعت" },
      { key: "وزن", value: "۲۴۵ گرم" },
    ],
    description:
      "دسته حرفه‌ای ریزر برای بازی رقابتی؛ دکمه‌های Mecha-Tactile و تریگرهای Hall Effect بدون لَپ پاسخ می‌دهند. تا ۱۰۰ ساعت باتری و اتصال بدون تأخیر، همراه همیشگی تورنمنت‌هاست.",
  },
  {
    key: "asus-rog-raikiri-pro",
    name: "دسته بازی ASUS ROG Raikiri Pro با نمایشگر OLED",
    nameEn: "ASUS ROG Raikiri Pro Controller",
    price: 5_480_000,
    stock: 0,
    categorySlug: "console-controller",
    brandName: "ایسوس ROG",
    image: IMG.conRog.main,
    gallery: [...IMG.conRog.gal],
    rating: 4.3,
    reviewCount: 38,
    soldCount: 22,
    sku: "GAM-CON-002",
    specs: [
      { key: "اتصال", value: "2.4GHz، بلوتوث و USB-C" },
      { key: "سازگاری", value: "Xbox و PC" },
      { key: "نمایشگر", value: "OLED کوچک" },
      { key: "دکمه پشتی", value: "۴ دکمه قابل تنظیم" },
      { key: "پروفایل", value: "۳ پروفایل ذخیره‌سازی" },
      { key: "لرزش", value: "موتور دوگانه" },
    ],
    description:
      "دسته هوشمند ROG با نمایشگر OLED و پروفایل‌های قابل‌حمل؛ کنترل کامل برای Xbox و PC در یک بدنه حرفه‌ای. چهار دکمه پشتی قابل تنظیم، در شووت‌های تن‌به‌تن مزیت واقعی می‌سازد.",
  },
  {
    key: "razer-iskur-v2",
    name: "صندلی گیمینگ Razer Iskur V2 با پشتی طبیاتی",
    nameEn: "Razer Iskur V2 Ergonomic Gaming Chair",
    price: 38_900_000,
    stock: 4,
    categorySlug: "gaming-chair-desk",
    brandName: "ریزر",
    image: IMG.chairRazer.main,
    gallery: [...IMG.chairRazer.gal],
    rating: 4.5,
    reviewCount: 83,
    soldCount: 41,
    isSpecial: true,
    sku: "GAM-CHR-001",
    specs: [
      { key: "فریم", value: "فلزی با گارانتی ۵ ساله" },
      { key: "پشتی", value: "طبیاتی با تنظیم ۶ جهته" },
      { key: "فوم", value: "فرم‌فیتینگ با لبه‌ی لیور" },
      { key: "روکش", value: "چرم مصنوعی چندلایه" },
      { key: "تنظیم شیب", value: "تا ۱۵۲ درجه" },
      { key: "قد مناسب", value: "۱۵۰ تا ۱۹۵ سانتی‌متر" },
    ],
    description:
      "صندلی گیمینگ ریزر با مکانیزم طبیاتی که ستون فقرات را در جلسات طولانی حمایت می‌کند. فوم فرم‌فیتینگ آن فشار نقاط حساس بدن را از بین می‌برد و خستگی را به تعویق می‌اندازد.",
  },
  {
    key: "corsair-platform-6-desk",
    name: "میز گیمینگ ماژولار Corsair Platform:6",
    nameEn: "Corsair Platform:6 Modular Gaming Desk",
    price: 32_500_000,
    discountPrice: 29_900_000,
    stock: 3,
    categorySlug: "gaming-chair-desk",
    brandName: "کورسیر",
    image: IMG.deskCorsair.main,
    gallery: [...IMG.deskCorsair.gal],
    rating: 4.4,
    reviewCount: 52,
    soldCount: 18,
    sku: "GAM-DESK-001",
    specs: [
      { key: "ابعاد", value: "۱۸۰×۷۶ سانتی‌متر" },
      { key: "ساختار", value: "دو ریل پایه ماژولار" },
      { key: "سطح", value: "دولایه با روکش ضدخش" },
      { key: "ارتفاع", value: "قابل تنظیم" },
      { key: "لوازم جانبی", value: "ریل نصب ماژولار" },
      { key: "مدیریت کابل", value: "شیار داخلی" },
    ],
    description:
      "میز ماژولار کورسیر که با ریل‌های قابل افزودن، هر ماه بزرگ‌تر می‌شود؛ استودیوی شخصی شماست. سطح دولایه و شیارهای مدیریت کابل، میز کار را همیشه مرتب و حرفه‌ای نگه می‌دارد.",
  },
  {
    key: "steelseries-arctis-nova-pro-wireless",
    name: "هدست گیمینگ SteelSeries Arctis Nova Pro Wireless",
    nameEn: "SteelSeries Arctis Nova Pro Wireless",
    price: 19_800_000,
    stock: 9,
    categorySlug: "headset-stream",
    brandName: "استیل‌سریز",
    image: IMG.hsSteel.main,
    gallery: [...IMG.hsSteel.gal],
    rating: 4.8,
    reviewCount: 312,
    soldCount: 175,
    featured: true,
    isSpecial: true,
    sku: "GAM-HS-001",
    specs: [
      { key: "درایور", value: "40mm نئودیمیوم" },
      { key: "پاسخ فرکانس", value: "10Hz تا 40kHz" },
      { key: "اتصال", value: "2.4GHz و بلوتوث هم‌زمان" },
      { key: "باتری", value: "سیستم دیتاسوئپ" },
      { key: "میکروفون", value: "قابل جمع‌شدن با نویزکنسلینگ" },
      { key: "ویژگی", value: "GameDAC گیمینگ" },
    ],
    description:
      "بهترین هدست بی‌سیم گیمینگ به انتخاب منتقدان؛ سیستم دیتاسوئپ یعنی باتری عملاً هیچ‌وقت تمام نمی‌شود. DAC داخلی و موقعیت‌یابی صوتی دقیق، آگاهی فضایی را به سطح جدیدی می‌رساند.",
  },
  {
    key: "logitech-g-pro-x-2-lightspeed",
    name: "هدست گیمینگ Logitech G Pro X 2 Lightspeed",
    nameEn: "Logitech G Pro X 2 Lightspeed",
    price: 13_400_000,
    discountPrice: 12_100_000,
    stock: 13,
    categorySlug: "headset-stream",
    brandName: "لاجیتک جی",
    image: IMG.hsLogi.main,
    gallery: [...IMG.hsLogi.gal],
    rating: 4.7,
    reviewCount: 265,
    soldCount: 330,
    sku: "GAM-HS-002",
    specs: [
      { key: "درایور", value: "50mm گرافن" },
      { key: "اتصال", value: "Lightspeed، بلوتوث و سیمی" },
      { key: "وزن", value: "۲۸۵ گرم" },
      { key: "باتری", value: "تا ۹۰ ساعت" },
      { key: "میکروفون", value: "۶mm قابل جدا شدن" },
      { key: "صدای فضایی", value: "DTS Headphone:X 2.0" },
    ],
    description:
      "هدست رسمی رقابت‌های ای‌اسپورت؛ درایورهای گرافن با پاسخ صوتی سریع و دقیق هر قدم حریف را لو می‌دهند. سه اتصال هم‌زمان و ۹۰ ساعت باتری، آزادی کامل تورنمنت‌ها را می‌دهد.",
  },
  {
    key: "hyperx-quadcast-s",
    name: "میکروفون استریم HyperX QuadCast S USB",
    nameEn: "HyperX QuadCast S USB Condenser Microphone",
    price: 5_350_000,
    stock: 16,
    categorySlug: "headset-stream",
    brandName: "هیپرایکس",
    image: IMG.micHyper.main,
    gallery: [...IMG.micHyper.gal],
    rating: 4.6,
    reviewCount: 198,
    soldCount: 420,
    featured: true,
    sku: "GAM-STR-001",
    specs: [
      { key: "نوع", value: "کاندنسر USB" },
      { key: "الگوی ضبط", value: "۴ حالت (استریو/اُمنی/بای/کاردیوئید)" },
      { key: "پاسخ فرکانس", value: "20Hz تا 20kHz" },
      { key: "نرخ نمونه", value: "96kHz / 24bit" },
      { key: "کنترل", value: "گین آنالوگ و دکمه بی‌صدا" },
      { key: "نور", value: "RGB با افکت شعله" },
    ],
    description:
      "میکروفون استاندارد استریمرها؛ چهار الگوی ضبط و افکت شعله RGB روی هر پخش زنده حرفه‌ای می‌نشیند. قاعده پایه داخلی و کنترل گین، صدای پخش را همیشه تمیز نگه می‌دارد.",
  },
];

/* ═══════════════════════ exported VerticalDef ═════════════════════ */
export const GAMING_CATALOG: VerticalDef = {
  id: "gaming",
  nameFa: "گیمینگ حرفه‌ای",
  nameEn: "Pro Gaming",
  templateId: "zentry-gaming",
  taglineFa: "دنیای حرفه‌ای‌های گیمینگ",
  descFa:
    "هر چیزی که یک گیمر حرفه‌ای لازم دارد — از کارت گرافیک و پردازنده تا مانیتور 4K، صندلی ارگونومیک و تجهیزات استریم — با قیمت واقعی و ضمانت اصالت کالا. رگ رویایی‌ات را همین‌جا، قطعه‌به‌قطعه بچین.",
  icon: "Gamepad2",
  aiPersona:
    "من مربی تجهیزات گیمینگ این فروشگاهم؛ قبل از هر پیشنهاد، ژانر بازی‌هات (FPS، MMO یا شبیه‌ساز)، بودجه و رزولوشن هدفت را می‌پرسم تا دقیق‌ترین ترکیب سخت‌افزار را برایت بچینم. از بحث فریم‌ریت، گلو گره سخت‌افزاری و انتخاب کارت گرافیک همون‌قدری سر در می‌آورم که از ست‌آپ استریم: میکروفون، دوربین، نور و اینترنت. هر قطعه‌ای که معرفی می‌کنم از محصولات همین فروشگاه است و مشخصاتش را با بازی هدفت تطبیق می‌دهم. اگر سوالی خارج از دنیای گیمینگ و تجهیزاتش بپرسی، محترمانه همان‌جا رد می‌کنم تا تمرکز روی بهترین انتخاب برای رزمت بماند. پس بگو چه بازی‌ای می‌کنی — قدم‌به‌قدم یه رگ بسازیم که حریف‌ها فقط فانوسش را ببینند!",
  categories: [
    {
      name: "کارت گرافیک",
      slug: "gpu",
      icon: "Gpu",
      description: "کارت‌های گرافیک NVIDIA و board partner های حرفه‌ای برای هر بودجه و رزولوشن",
      sortOrder: 1,
    },
    {
      name: "پردازنده",
      slug: "cpu",
      icon: "Cpu",
      description: "پردازنده‌های گیمینگ اینتل و AMD با بالاترین فریم‌ریت به ازای هر تومان",
      sortOrder: 2,
    },
    {
      name: "مادربرد و رم",
      slug: "motherboard-ram",
      icon: "CircuitBoard",
      description: "مادربردهای گیمینگ و رم‌های DDR5 پرسرعت با نور ARGB",
      sortOrder: 3,
    },
    {
      name: "لپ‌تاپ گیمینگ",
      slug: "gaming-laptop",
      icon: "Laptop",
      description: "لپ‌تاپ‌های ROG و Katana با گرافیک سری RTX 40",
      sortOrder: 4,
    },
    {
      name: "مانیتور گیمینگ",
      slug: "gaming-monitor",
      icon: "Monitor",
      description: "مانیتورهای پرسرعت 144 تا 180Hz و پرچمداران 4K",
      sortOrder: 5,
    },
    {
      name: "کیس و خنک‌کننده",
      slug: "case-cooling",
      icon: "Fan",
      description: "کیس‌های شیشه‌ای RGB و خنک‌کننده‌های مایع تا رادیاتور 360",
      sortOrder: 6,
    },
    {
      name: "کنسول و دسته",
      slug: "console-controller",
      icon: "Gamepad2",
      description: "دسته‌های حرفه‌ای رقابتی برای کنسول و PC",
      sortOrder: 7,
    },
    {
      name: "صندلی و میز گیمینگ",
      slug: "gaming-chair-desk",
      icon: "Armchair",
      description: "صندلی‌های طبیاتی و میزهای ماژولار برای جلسات طولانی",
      sortOrder: 8,
    },
    {
      name: "هدست و لوازم استریم",
      slug: "headset-stream",
      icon: "Headphones",
      description: "هدست‌های گیمینگ، میکروفون و تجهیزات پخش زنده",
      sortOrder: 9,
    },
  ],
  brands: [
    { name: "انویدیا", slug: "nvidia" },
    { name: "ایسوس ROG", slug: "asus-rog" },
    { name: "ام اس آی", slug: "msi" },
    { name: "ریزر", slug: "razer" },
    { name: "لاجیتک جی", slug: "logitech-g" },
    { name: "کورسیر", slug: "corsair" },
    { name: "هیپرایکس", slug: "hyperx" },
    { name: "استیل‌سریز", slug: "steelseries" },
  ],
  products: PRODUCTS,
};
