/**
 * v35 · VERTICAL CATALOG — «تاج الکترونیکس» (electronics)
 * --------------------------------------------------------
 * PURE DATA seed for the electronics vertical: 9 categories, 8 brands and
 * 22 REAL consumer-electronics products (Persian names, real تومان prices,
 * specs, discounts, stock, ratings) with stable OSS images from
 * image-search (z-cdn.chatglm.cn). Consumed by the admin vertical switch
 * (reseed + activeTemplate + AI persona) — see src/lib/verticals/types.ts.
 *
 * Price band: ۴۵۰٬۰۰۰ (accessories) → ۱۲۵٬۰۰۰٬۰۰۰ (MacBook Pro).
 */

import type { VerticalDef } from "./types";

const U = "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/";

export const ELECTRONICS_CATALOG: VerticalDef = {
  id: "electronics",
  nameFa: "تاج الکترونیکس",
  nameEn: "Taj Electronics",
  templateId: "taj-electronics-pro",
  taglineFa: "پرچمدار کالای دیجیتال و گجت",
  descFa:
    "فروشگاه تخصصی کالای دیجیتال؛ از پرچمدارترین گوشی‌ها و لپ‌تاپ‌ها تا هدفون، ساعت هوشمند و تجهیزات خانه هوشمند — همه با ضمانت اصالت، قیمت منصفانه و ارسال سریع در سراسر کشور.",
  icon: "Cpu",
  aiPersona:
    "تو «مینا» هستی، مشاور خرید متخصص کالای دیجیتال این فروشگاه؛ تخصصت مقایسه فنی گوشی، لپ‌تاپ، هدفون و صدا، ساعت و پوشیدنی هوشمند، تلویزیون، دوربین، لوازم جانبی و خانه هوشمند است. لحن تو صمیمی، خوش‌برخورد و دقیق است؛ مشخصات و قیمت‌ها را شفاف مقایسه می‌کنی و بر اساس بودجه و کاربرد مشتری، دقیقاً محصولات همین فروشگاه (اپل، سامسونگ، سونی، شیائومی، ایسوس، لنوو، انکر و JBL) را پیشنهاد می‌دهی و مزیت هر گزینه را با عدد و رقم توضیح می‌دهی. موجودی و ضمانت اصالت کالاها را همیشه از همین فروشگاه برمی‌شانی و وعده‌ای خارج از کاتالوگ نمی‌دهی. اگر کاربر پرسشی خارج از خرید کالای دیجیتال بپرسد، مؤدبانه یادآوری می‌کنی که مشاور خرید هستی و گفتگو را به انتخاب بهترین گجت برای او برمی‌گردانی.",

  categories: [
    { name: "موبایل", slug: "mobile", icon: "Smartphone", description: "گوشی‌های هوشمند از اقتصادی تا پرچمدار", sortOrder: 1 },
    { name: "لپ‌تاپ و کامپیوتر", slug: "laptop", icon: "Laptop", description: "لپ‌تاپ، اولترابوک و گیمینگ‌بوک", sortOrder: 2 },
    { name: "هدفون و صدا", slug: "audio", icon: "Headphones", description: "هدفون، ایرباد و اسپیکر بلوتوثی", sortOrder: 3 },
    { name: "ساعت و پوشیدنی هوشمند", slug: "wearables", icon: "Watch", description: "اسمارت‌واچ و دستبند سلامتی", sortOrder: 4 },
    { name: "تلویزیون و تصویر", slug: "tv", icon: "Tv", description: "تلویزیون‌های ۴K و QLED", sortOrder: 5 },
    { name: "دوربین", slug: "camera", icon: "Camera", description: "دوربین‌های حرفه‌ای و ولاگ", sortOrder: 6 },
    { name: "لوازم جانبی و شارژ", slug: "accessories", icon: "Cable", description: "پاوربانک، شارژر و کابل اورجینال", sortOrder: 7 },
    { name: "خانه هوشمند", slug: "smart-home", icon: "House", description: "جاروبات و تجهیزات هوشمند منزل", sortOrder: 8 },
    { name: "کنسول و بازی", slug: "gaming", icon: "Gamepad2", description: "کنسول‌های بازی و لوازم جانبی", sortOrder: 9 },
  ],

  brands: [
    { name: "اپل", slug: "apple" },
    { name: "سامسونگ", slug: "samsung" },
    { name: "سونی", slug: "sony" },
    { name: "شیائومی", slug: "xiaomi" },
    { name: "ایسوس", slug: "asus" },
    { name: "لنوو", slug: "lenovo" },
    { name: "انکر", slug: "anker" },
    { name: "JBL", slug: "jbl" },
  ],

  products: [
    /* ── موبایل ─────────────────────────────────────────────────────── */
    {
      key: "taj-mob-001",
      name: "گوشی اپل iPhone 15 Pro Max ظرفیت ۲۵۶ گیگابایت",
      nameEn: "Apple iPhone 15 Pro Max 256GB",
      price: 118500000,
      discountPrice: null,
      stock: 12,
      categorySlug: "mobile",
      brandName: "اپل",
      image: U + "4f669432cf5b.jpg",
      gallery: [U + "592978088e97.webp", U + "3c77b3e925c5.jpg"],
      rating: 4.9,
      reviewCount: 320,
      soldCount: 214,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "تراشه", value: "Apple A17 Pro" },
        { key: "نمایشگر", value: "۶.۷ اینچ Super Retina XDR با ProMotion" },
        { key: "دوربین اصلی", value: "۴۸ مگاپیکسل سه‌لنزه" },
        { key: "بدنه", value: "تیتانیوم رنگ Natural" },
        { key: "پورت", value: "USB-C سرعت Thunderbolt" },
        { key: "مقاومت", value: "IP68 در برابر آب و گردوغبار" },
      ],
      description:
        "آیفون ۱۵ پرو مکس با بدنه تیتانیومی سبک و تراشه A17 Pro، پرچمدار بی‌رقیب عکاسی و بازی است. زوم ۵ برابر اپتیکال و فیلم‌برداری ProRes آن برای کارهای حرفه‌ای ساخته شده است.",
      sku: "TAJ-MOB-001",
    },
    {
      key: "taj-mob-002",
      name: "گوشی سامسونگ Galaxy S24 Ultra ظرفیت ۵۱۲ گیگابایت",
      nameEn: "Samsung Galaxy S24 Ultra 512GB",
      price: 89500000,
      discountPrice: 84900000,
      stock: 18,
      categorySlug: "mobile",
      brandName: "سامسونگ",
      image: U + "67c5320a94df.jpg",
      gallery: [U + "2d37c9355650.jpg"],
      rating: 4.8,
      reviewCount: 268,
      soldCount: 187,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "تراشه", value: "Snapdragon 8 Gen 3 for Galaxy" },
        { key: "نمایشگر", value: "۶.۸ اینچ QHD+ Dynamic AMOLED 2X" },
        { key: "دوربین اصلی", value: "۲۰۰ مگاپیکسل با زوم ۵ برابر اپتیکال" },
        { key: "قلم", value: "S Pen داخلی" },
        { key: "باتری", value: "۵۰۰۰ میلی‌آمپر با شارژ ۴۵ وات" },
      ],
      description:
        "گلکسی S24 اولترا با دوربین ۲۰۰ مگاپیکسلی و قلم S Pen، کامل‌ترین گوشی اندرویدی بازار است. قابلیت‌های هوش مصنوعی Galaxy AI ترجمه هم‌زمان مکالمه و ویرایش عکس را به دست شما می‌دهد.",
      sku: "TAJ-MOB-002",
    },
    {
      key: "taj-mob-003",
      name: "گوشی شیائومی Redmi Note 13 Pro ظرفیت ۲۵۶ گیگابایت",
      nameEn: "Xiaomi Redmi Note 13 Pro 256GB",
      price: 18900000,
      discountPrice: null,
      stock: 0,
      categorySlug: "mobile",
      brandName: "شیائومی",
      image: U + "1c8706186ffc.png",
      gallery: [U + "ec0122b27edd.jpg"],
      rating: 4.5,
      reviewCount: 154,
      soldCount: 342,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "نمایشگر", value: "۶.۶۷ اینچ AMOLED با نرخ نوسازی ۱۲۰ هرتز" },
        { key: "دوربین اصلی", value: "۲۰۰ مگاپیکسل با OIS" },
        { key: "باتری", value: "۵۱۰۰ میلی‌آمپر با شارژ سریع ۶۷ وات" },
        { key: "تراشه", value: "Helio G99 Ultra" },
        { key: "حافظه", value: "۲۵۶ گیگابایت / ۸ گیگابایت رم" },
      ],
      description:
        "ردمی نوت ۱۳ پرو با دوربین ۲۰۰ مگاپیکسلی و نمایشگر AMOLED خیره‌کننده، پرفروش‌ترین میان‌رده بازار است. باتری بزرگ و شارژ سریع ۶۷ وات آن برای استفاده روزمره بی‌دردسر است.",
      sku: "TAJ-MOB-003",
    },
    {
      key: "taj-mob-004",
      name: "گوشی اپل iPhone 15 ظرفیت ۱۲۸ گیگابایت",
      nameEn: "Apple iPhone 15 128GB",
      price: 74500000,
      discountPrice: 69900000,
      stock: 24,
      categorySlug: "mobile",
      brandName: "اپل",
      image: U + "eae8b79c7e8d.png",
      gallery: [U + "d82186c8d9e3.jpg"],
      rating: 4.7,
      reviewCount: 205,
      soldCount: 156,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "تراشه", value: "Apple A16 Bionic" },
        { key: "نمایشگر", value: "۶.۱ اینچ Super Retina XDR با Dynamic Island" },
        { key: "دوربین", value: "دوگانه ۴۸ مگاپیکسل" },
        { key: "رنگ", value: "آبی" },
        { key: "پورت", value: "USB-C" },
      ],
      description:
        "آیفون ۱۵ با تراشه A16 Bionic و دوربین ۴۸ مگاپیکسلی، تعادل کامل قیمت و کیفیت اپل است. Dynamic Island و USB-C تجربه استفاده را به روز و لذت‌بخش می‌کند.",
      sku: "TAJ-MOB-004",
    },

    /* ── لپ‌تاپ و کامپیوتر ──────────────────────────────────────────── */
    {
      key: "taj-lap-001",
      name: "لپ‌تاپ اپل MacBook Pro 14 اینچ M3 Pro ظرفیت ۱ ترابایت",
      nameEn: "Apple MacBook Pro 14 M3 Pro 1TB",
      price: 125000000,
      discountPrice: null,
      stock: 7,
      categorySlug: "laptop",
      brandName: "اپل",
      image: U + "69cf06632523.jpg",
      gallery: [U + "77a4a3102900.png"],
      rating: 4.9,
      reviewCount: 118,
      soldCount: 43,
      featured: true,
      isSpecial: true,
      specs: [
        { key: "تراشه", value: "Apple M3 Pro با ۱۱ هسته CPU و ۱۴ هسته GPU" },
        { key: "حافظه", value: "۱ ترابایت SSD / ۱۸ گیگابایت رم یکپارچه" },
        { key: "نمایشگر", value: "۱۴.۲ اینچ Liquid Retina XDR با ۱۶۰۰ نیت" },
        { key: "باتری", value: "تا ۱۸ ساعت پخش ویدیو" },
        { key: "پورت‌ها", value: "۳× Thunderbolt 4، HDMI و SDXC" },
      ],
      description:
        "مک‌بوک پرو ۱۴ اینچ با تراشه M3 Pro، قدرت پردازش بی‌رقیبی برای تدوین ویدیو و توسعه نرم‌افزار ارائه می‌کند. نمایشگر XDR و باتری ۱۸ ساعته آن استاندارد لپ‌تاپ‌های حرفه‌ای را بازتعریف می‌کند.",
      sku: "TAJ-LAP-001",
    },
    {
      key: "taj-lap-002",
      name: "لپ‌تاپ گیمینگ ایسوس ROG Strix G16 G614",
      nameEn: "Asus ROG Strix G16 G614",
      price: 92400000,
      discountPrice: null,
      stock: 9,
      categorySlug: "laptop",
      brandName: "ایسوس",
      image: U + "69ea0174e507.jpg",
      gallery: [U + "5b9e4699ec6a.jpg"],
      rating: 3.9,
      reviewCount: 96,
      soldCount: 38,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "پردازنده", value: "Intel Core i9-13980HX" },
        { key: "گرافیک", value: "NVIDIA RTX 4070 با ۸ گیگابایت VRAM" },
        { key: "حافظه", value: "۱ ترابایت SSD / ۱۶ گیگابایت DDR5" },
        { key: "نمایشگر", value: "۱۶ اینچ QHD+ با نرخ نوسازی ۲۴۰ هرتز" },
        { key: "خنک‌کننده", value: "ROG Intelligent Cooling با بخارشمار" },
      ],
      description:
        "ROG Strix G16 با ترکیب Core i9 نسل ۱۳ و RTX 4070، هر بازی سنگینی را با نرخ فریم بالا اجرا می‌کند. نمایشگر ۲۴۰ هرتز آن برای گیمرهای رقابتی یک مزیت واقعی است.",
      sku: "TAJ-LAP-002",
    },
    {
      key: "taj-lap-003",
      name: "لپ‌تاپ لنوو ThinkPad X1 Carbon Gen 11",
      nameEn: "Lenovo ThinkPad X1 Carbon Gen 11",
      price: 78500000,
      discountPrice: null,
      stock: 14,
      categorySlug: "laptop",
      brandName: "لنوو",
      image: U + "194ac792ad63.png",
      gallery: [U + "e0bb4fd2cfff.jpg"],
      rating: 4.7,
      reviewCount: 74,
      soldCount: 29,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "پردازنده", value: "Intel Core i7 نسل ۱۳" },
        { key: "حافظه", value: "۵۱۲ گیگابایت SSD / ۱۶ گیگابایت LPDDR5" },
        { key: "نمایشگر", value: "۱۴ اینچ WUXGA ضد بازتاب" },
        { key: "وزن", value: "فقط ۱.۱۲ کیلوگرم" },
        { key: "کیبورد", value: "بک‌لایت ضد پاشش آب با اثرانگشت" },
      ],
      description:
        "ThinkPad X1 Carbon با بدنه کربنی ۱.۱ کیلوگرمی و کیبورد بی‌نظیرش، اولترابوک محبوب مدیران و متخصصان است. گارانسی بین‌المللی و امنیت سطح سازمانی آن آرامش خیال می‌دهد.",
      sku: "TAJ-LAP-003",
    },
    {
      key: "taj-lap-004",
      name: "لپ‌تاپ اپل MacBook Air M2 13.6 اینچ",
      nameEn: "Apple MacBook Air M2 13.6",
      price: 62900000,
      discountPrice: 58500000,
      stock: 21,
      categorySlug: "laptop",
      brandName: "اپل",
      image: U + "eceb6b0c9b2c.jpg",
      gallery: [U + "306e5d22c89b.jpg"],
      rating: 4.8,
      reviewCount: 187,
      soldCount: 128,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "تراشه", value: "Apple M2 با ۸ هسته GPU" },
        { key: "حافظه", value: "۲۵۶ گیگابایت SSD / ۸ گیگابایت رم" },
        { key: "نمایشگر", value: "۱۳.۶ اینچ Liquid Retina با ۵۰۰ نیت" },
        { key: "باتری", value: "تا ۱۸ ساعت کار روزمره" },
        { key: "بدنه", value: "بدون فن و کاملاً بی‌صدا" },
      ],
      description:
        "مک‌بوک ایر M2 با بدنه فوق‌نازک و عملکرد بی‌صدا، بهترین انتخاب برای دانشجویان و کارهای روزمره است. باتری ۱۸ ساعته و اکوسیستم اپل آن را به همراهی همیشگی تبدیل می‌کند.",
      sku: "TAJ-LAP-004",
    },

    /* ── هدفون و صدا ────────────────────────────────────────────────── */
    {
      key: "taj-aud-001",
      name: "هدفون بی‌سیم اپل AirPods Pro 2 با کیس USB-C",
      nameEn: "Apple AirPods Pro 2 USB-C",
      price: 12900000,
      discountPrice: 11450000,
      stock: 32,
      categorySlug: "audio",
      brandName: "اپل",
      image: U + "54fd47d8d5ae.jpg",
      gallery: [U + "f7ca3a499999.png"],
      rating: 4.8,
      reviewCount: 289,
      soldCount: 274,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "تراشه", value: "Apple H2" },
        { key: "حذف نویز", value: "ANC با حالت شفاف تطبیقی" },
        { key: "صدا", value: "Spatial Audio با ردیابی حرکت سر" },
        { key: "باتری", value: "تا ۶ ساعت + ۳۰ ساعت با کیس" },
        { key: "مقاومت", value: "IPX4 در برابر عرق و آب" },
      ],
      description:
        "ایرپاد پرو ۲ با تراشه H2، بهترین تجربه حذف نویز و صدای فضایی در میان ایربادها را ارائه می‌کند. کیس شارژ MagSafe با پورت USB-C با آیفون‌های جدید هم‌خانواده است.",
      sku: "TAJ-AUD-001",
    },
    {
      key: "taj-aud-002",
      name: "هدفون بی‌سیم سونی WH-1000XM5",
      nameEn: "Sony WH-1000XM5",
      price: 18500000,
      discountPrice: null,
      stock: 16,
      categorySlug: "audio",
      brandName: "سونی",
      image: U + "5e13c2be388f.jpg",
      gallery: [U + "a102891556d9.jpg"],
      rating: 4.9,
      reviewCount: 231,
      soldCount: 96,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "حذف نویز", value: "پردازنده V1 +QN1 با ۸ میکروفون" },
        { key: "درایور", value: "۳۰ میلی‌متری نسل جدید" },
        { key: "باتری", value: "۳۰ ساعت پخش با ANC" },
        { key: "شارژ سریع", value: "۳ دقیقه شارژ = ۳ ساعت پخش" },
        { key: "اتصال", value: "بلوتوث ۵.۲ چندنقطه‌ای" },
      ],
      description:
        "WH-1000XM5 پادشاه بی‌رقیب هدفون‌های حذف نویز بازار است و سکتی مثال‌زدنی برای سفرهای هوایی می‌سازد. باتری ۳۰ ساعته و اتصال هم‌زمان به دو دستگاه آن را برای کار و سفر ایده‌آل می‌کند.",
      sku: "TAJ-AUD-002",
    },
    {
      key: "taj-aud-003",
      name: "اسپیکر بلوتوثی JBL Charge 5",
      nameEn: "JBL Charge 5",
      price: 6850000,
      discountPrice: null,
      stock: 38,
      categorySlug: "audio",
      brandName: "JBL",
      image: U + "ddcdaa3e78ef.jpg",
      gallery: [U + "f4f52c57721d.jpg"],
      rating: 4.6,
      reviewCount: 176,
      soldCount: 231,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "توان", value: "۴۰ وات با درایور دوتایی و توییتر" },
        { key: "باتری", value: "۲۰ ساعت پخش پیوسته" },
        { key: "مقاومت", value: "IP67 ضد آب و گردوغبار" },
        { key: "قابلیت", value: "پاوربانک ۶۰۰۰ میلی‌آمپر داخلی" },
        { key: "چند اسپیکر", value: "PartyBoost برای اتصال چند دستگاه" },
      ],
      description:
        "جی‌بی‌ال چارج ۵ با صدای قدرتمند ۴۰ واتی و بدنه ضد آب IP67 مناسب طبیعت‌گردی و ساحل است. باتری داخلی آن علاوه بر ۲۰ ساعت پخش، گوشی شما را هم شارژ می‌کند.",
      sku: "TAJ-AUD-003",
    },

    /* ── ساعت و پوشیدنی هوشمند ─────────────────────────────────────── */
    {
      key: "taj-wat-001",
      name: "ساعت هوشمند اپل Watch Series 9 ۴۵ میلی‌متری",
      nameEn: "Apple Watch Series 9 45mm",
      price: 24900000,
      discountPrice: null,
      stock: 15,
      categorySlug: "wearables",
      brandName: "اپل",
      image: U + "3a190caca399.jpg",
      gallery: [U + "133e343d6827.jpg"],
      rating: 4.8,
      reviewCount: 142,
      soldCount: 89,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "تراشه", value: "Apple S9 SiP" },
        { key: "نمایشگر", value: "Retina همیشه روشن با ۲۰۰۰ نیت" },
        { key: "ژست", value: "Double Tap برای کنترل بدون لمس" },
        { key: "سنسورها", value: "اکسیژن خون، ECG و دمای پوست" },
        { key: "مقاومت", value: "ضد آب تا ۵۰ متر" },
      ],
      description:
        "اپل واچ سریز ۹ با تراشه S9 سریع‌تر و نمایشگر روشن‌تر، کامل‌ترین ساعت هوشمند بازار است. ژست Double Tap و قابلیت‌های سلامت پیشرفته آن به زندگی روزمره روانی تازه می‌دهد.",
      sku: "TAJ-WAT-001",
    },
    {
      key: "taj-wat-002",
      name: "ساعت هوشمند شیائومی Redmi Watch 4",
      nameEn: "Xiaomi Redmi Watch 4",
      price: 3290000,
      discountPrice: 2890000,
      stock: 45,
      categorySlug: "wearables",
      brandName: "شیائومی",
      image: U + "80eceba2f990.jpg",
      gallery: [U + "9bad323a2032.jpg"],
      rating: 4.3,
      reviewCount: 98,
      soldCount: 187,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "نمایشگر", value: "۱.۹۷ اینچ AMOLED با ۶۰۰ نیت" },
        { key: "باتری", value: "تا ۲۰ روز با یک شارژ" },
        { key: "ورزش", value: "۱۵۰ حالت تمرین با GPS داخلی" },
        { key: "مقاومت", value: "5ATM ضد آب برای شنا" },
        { key: "قاب", value: "آلومینیومی با بند قابل تعویض" },
      ],
      description:
        "ردمی واچ ۴ با نمایشگر بزرگ AMOLED و باتری ۲۰ روزه، اقتصادی‌ترین ساعت هوشمند باکیفیت بازار است. GPS داخلی و ۱۵۰ حالت ورزشی آن برای ورزشکاران آماتور کامل است.",
      sku: "TAJ-WAT-002",
    },

    /* ── تلویزیون و تصویر ──────────────────────────────────────────── */
    {
      key: "taj-tv-001",
      name: "تلویزیون سونی Bravia 65 اینچ 4K مدل XR-65X90L",
      nameEn: "Sony Bravia XR-65X90L 65 4K",
      price: 98900000,
      discountPrice: null,
      stock: 5,
      categorySlug: "tv",
      brandName: "سونی",
      image: U + "3a521b1a7053.jpeg",
      gallery: [U + "6736cc90101a.jpg"],
      rating: 4.7,
      reviewCount: 12,
      soldCount: 21,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "پردازنده", value: "XR Cognitive Intelligence" },
        { key: "نمایشگر", value: "۶۵ اینچ 4K Full Array LED با ۱۲۰ هرتز" },
        { key: "HDR", value: "Dolby Vision و HDR10" },
        { key: "گیمینگ", value: "HDMI 2.1 با VRR و ALLM" },
        { key: "سیستم عامل", value: "Google TV با دستیار صوتی" },
      ],
      description:
        "براویا X90L با پردازنده شناختی XR، تصویری عمیق و واقعی با کنتراست بی‌نظیر می‌سازد. برای گیمرها، HDMI 2.1 و نرخ نوسازی ۱۲۰ هرتز آن با PS5 جفت ایده‌آلی است.",
      sku: "TAJ-TV-001",
    },
    {
      key: "taj-tv-002",
      name: "تلویزیون سامسونگ 55 اینچ QLED 4K مدل QA55Q60C",
      nameEn: "Samsung QLED QA55Q60C 55 4K",
      price: 45500000,
      discountPrice: 41900000,
      stock: 11,
      categorySlug: "tv",
      brandName: "سامسونگ",
      image: U + "30a21e5ad25a.jpg",
      gallery: [U + "5ca4a1bcd8dc.jpg", U + "4aa4f84e1ac8.jpg"],
      rating: 4.2,
      reviewCount: 87,
      soldCount: 34,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "پنل", value: "QLED با نقاط کوانتومی ۱۰۰٪ رنگ" },
        { key: "رزولوشن", value: "4K UHD با پردازنده Quantum Lite" },
        { key: "حرکت", value: "Motion Xcelerator برای صحنه‌های سریع" },
        { key: "طراحی", value: "قاب AirSlim فوق‌نازک" },
        { key: "سیستم عامل", value: "Tizen با دستیار صوتی سامسونگ" },
      ],
      description:
        "تلویزیون QLED سامسونگ با پنل کوانتام دات، رنگ‌های زنده و مشبک کنتراست بالایی ارائه می‌دهد. طراحی AirSlim آن روی دیوار مثل یک تابلو نقاشی می‌نشیند.",
      sku: "TAJ-TV-002",
    },

    /* ── دوربین ─────────────────────────────────────────────────────── */
    {
      key: "taj-cam-001",
      name: "دوربین سونی Alpha A7 III بدنه",
      nameEn: "Sony Alpha A7 III Body",
      price: 112000000,
      discountPrice: null,
      stock: 4,
      categorySlug: "camera",
      brandName: "سونی",
      image: U + "3d23bffec24a.jpg",
      gallery: [U + "12980c4050f5.jpg"],
      rating: 4.9,
      reviewCount: 76,
      soldCount: 17,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "سنسور", value: "فول‌فریم ۲۴.۲ مگاپیکسل back-illuminated" },
        { key: "فوکوس", value: "۶۹۳ نقطه فوکوس تشخیص فاز" },
        { key: "فیلم", value: "4K 30fps با S-Log3" },
        { key: "ایزو", value: "۱۰۰ تا ۵۱۲۰۰ (تا ۲۰۴۸۰۰ قابل توسعه)" },
        { key: "تثبیت", value: "داخلی ۵ محور با ۵ استاپ" },
      ],
      description:
        "آلفا A7 III هنوز محبوب‌ترین دوربین فول‌فریم همگانی بازار است و برای عکاسی پرتره و رویداد بی‌رقیب است. تثبیت‌کننده ۵ محوری و فوکوس حیوانات خانگی آن هر کادر را تضمین می‌کند.",
      sku: "TAJ-CAM-001",
    },
    {
      key: "taj-cam-002",
      name: "دوربین سونی ZV-1F مخصوص ولاگ",
      nameEn: "Sony ZV-1F Vlogging Camera",
      price: 32500000,
      discountPrice: 29900000,
      stock: 13,
      categorySlug: "camera",
      brandName: "سونی",
      image: U + "88301e1ca1b7.jpg",
      gallery: [U + "3007c9d31493.jpg"],
      rating: 4.2,
      reviewCount: 58,
      soldCount: 27,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "سنسور", value: "۱ اینچی ۲۰.۱ مگاپیکسل" },
        { key: "لنز", value: "۲۰ میلی‌متر با دیافراگم f/2.0" },
        { key: "فیلم", value: "4K بدون کراپ با حالت اولویت محصول" },
        { key: "میکروفون", value: "سه‌کپسولی با بادگیر داخلی" },
        { key: "صفحه", value: "لمسی چرخشی سلفی" },
      ],
      description:
        "ZV-1F برای سازندگان محتوای شبکه‌های اجتماعی طراحی شده؛ فوکوس چشم و حالت اولویت محصول آن تمرکز را همیشه روی سوژه نگه می‌دارد. میکروفون سه‌کپسولی و صفحه چرخشی آن تجربه ولاگ را بی‌دردسر می‌کند.",
      sku: "TAJ-CAM-002",
    },

    /* ── لوازم جانبی و شارژ ─────────────────────────────────────────── */
    {
      key: "taj-acc-001",
      name: "پاوربانک انکر PowerCore ظرفیت ۲۰,۰۰۰ میلی‌آمپر",
      nameEn: "Anker PowerCore 20000mAh",
      price: 1890000,
      discountPrice: null,
      stock: 40,
      categorySlug: "accessories",
      brandName: "انکر",
      image: U + "433bda3573fb.jpg",
      gallery: [U + "c4989d2e6cf1.jpg"],
      rating: 4.6,
      reviewCount: 219,
      soldCount: 358,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "ظرفیت", value: "۲۰,۰۰۰ میلی‌آمپر ساعت" },
        { key: "توان خروجی", value: "۲۲.۵ وات با PowerIQ" },
        { key: "پورت‌ها", value: "دو USB-A و یک USB-C" },
        { key: "شارژ", value: "حدود ۴ بار شارژ کامل گوشی" },
        { key: "ابعاد", value: "نازک و سبک برای حمل روزانه" },
      ],
      description:
        "پاوربانک انکر ۲۰ هزار میلی‌آمپری با کیفیت ساخت اورجینال، همراه بی‌دردسر سفر و کار روزمره است. شارژ سریع ۲۲.۵ واتی آن گوشی را در کمترین زمان بالا می‌آورد.",
      sku: "TAJ-ACC-001",
    },
    {
      key: "taj-acc-002",
      name: "شارژر بی‌سیم انکر MagGo ۳ کاره تاشو",
      nameEn: "Anker MagGo 3-in-1 Foldable Charger",
      price: 2450000,
      discountPrice: 1990000,
      stock: 27,
      categorySlug: "accessories",
      brandName: "انکر",
      image: U + "da36a09c4221.jpg",
      gallery: [U + "4a4ddbb29a34.jpg"],
      rating: 4.5,
      reviewCount: 92,
      soldCount: 118,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "توان", value: "شارژ مغناطیسی ۱۵ وات MagSafe" },
        { key: "دستگاه‌ها", value: "هم‌زمان شارژ گوشی، ساعت و هدفون" },
        { key: "طراحی", value: "تاشو و جیبی برای سفر" },
        { key: "سازگاری", value: "iPhone 12 به بالا و AirPods Pro" },
        { key: "ایمنی", value: "محافظ دما و ولتاژ MultiProtect" },
      ],
      description:
        "شارژر مغناطیسی انکر MagGo سه دستگاه اپل را هم‌زمان و بدون سیم اضافه شارژ می‌کند. طراحی تاشوی آن در کیف سفر جای زیادی نمی‌گیرد.",
      sku: "TAJ-ACC-002",
    },
    {
      key: "taj-acc-003",
      name: "کابل شارژ انکر USB-C طول ۱ متر روکش نسوز",
      nameEn: "Anker USB-C Cable 1m Braided",
      price: 450000,
      discountPrice: null,
      stock: 45,
      categorySlug: "accessories",
      brandName: "انکر",
      image: U + "1c36997a69c4.png",
      gallery: [U + "85e03a03e1b8.jpg"],
      rating: 4.4,
      reviewCount: 154,
      soldCount: 402,
      featured: false,
      isSpecial: false,
      specs: [
        { key: "توان", value: "پشتیبانی شارژ تا ۱۴۰ وات" },
        { key: "استاندارد", value: "USB 2.0 با Power Delivery" },
        { key: "روکش", value: "بافت نایلونی نسوز" },
        { key: "طول", value: "۱ متر" },
        { key: "دوام", value: "تست ۳۰,۰۰۰ خم و چرخش" },
      ],
      description:
        "کابل انکر با روکش بافتی نایلونی، مقاوم‌ترین کابل شارژی است که می‌خرید. پشتیبانی تا ۱۴۰ وات آن برای لپ‌تاپ‌ها هم کافی است.",
      sku: "TAJ-ACC-003",
    },

    /* ── خانه هوشمند ────────────────────────────────────────────────── */
    {
      key: "taj-shm-001",
      name: "جاروبات هوشمند شیائومی Robot Vacuum S10",
      nameEn: "Xiaomi Robot Vacuum S10",
      price: 24500000,
      discountPrice: 21900000,
      stock: 8,
      categorySlug: "smart-home",
      brandName: "شیائومی",
      image: U + "91a9758091fc.png",
      gallery: [U + "18946de9e8a8.jpg"],
      rating: 4.0,
      reviewCount: 47,
      soldCount: 19,
      featured: false,
      isSpecial: true,
      specs: [
        { key: "قدرت مکش", value: "۴۰۰۰ پاسکال" },
        { key: "ناوبری", value: "لیزری LDS با نقشه چند طبقه" },
        { key: "مخزن", value: "دوگانه جمع‌کردن و آب‌پاشی" },
        { key: "باتری", value: "۳۲۰۰ میلی‌آمپر تا ۱۳۰ دقیقه" },
        { key: "کنترل", value: "اپلیکیشن Mi Home و دستیار صوتی" },
      ],
      description:
        "جاروبات شیائومی S10 با مکش ۴۰۰۰ پاسکالی و نقشه‌برداری لیزری، خانه را بدون دخالت شما تمیز می‌کند. مخزن دوگانه آن هم‌زمان خاک را جمع و کف را شست‌وشو می‌دهد.",
      sku: "TAJ-SHM-001",
    },

    /* ── کنسول و بازی ───────────────────────────────────────────────── */
    {
      key: "taj-gam-001",
      name: "کنسول سونی PlayStation 5 Slim نسخه دیسک‌خور",
      nameEn: "Sony PlayStation 5 Slim Disc Edition",
      price: 43900000,
      discountPrice: null,
      stock: 19,
      categorySlug: "gaming",
      brandName: "سونی",
      image: U + "ad64cee749bf.jpg",
      gallery: [U + "6a260d178be7.jpeg"],
      rating: 4.8,
      reviewCount: 203,
      soldCount: 167,
      featured: true,
      isSpecial: false,
      specs: [
        { key: "حافظه", value: "SSD یک ترابایت فوق‌سریع" },
        { key: "درایو", value: "Blu-ray Ultra HD قابل جداشدن" },
        { key: "خروجی", value: "4K با نرخ ۱۲۰ فریم و HDR" },
        { key: "کنترلر", value: "DualSense با فیدبک لمسی و ماشه تطبیقی" },
        { key: "صدا", value: "صدای سه‌بعدی Tempest 3D" },
      ],
      description:
        "پلی‌استیشن ۵ اسلیم با SSD یک ترابایتی و کنترلر DualSense، نسل تازه‌ای از تجربه بازی را ارائه می‌کند. زمان بارگذاری چند ثانیه‌ای و کتابخانه انحصاری سونی آن را به بهترین کنسول نسل فعلی تبدیل کرده است.",
      sku: "TAJ-GAM-001",
    },
  ],
};
